// --- COMPETITION SYLLABUS ---

const COMPETITION_POLITY = [
"1. भारतीय संविधान के विकास का संक्षिप्त इतिहास",
"2. भारतीय संविधान सभा",
"3. भारतीय संविधान की उद्देशिका अथवा प्रस्तावना",
"4. भारतीय संविधान के विदेशी स्रोत",
"5. भारतीय संविधान की अनुसूची",
"6. देशी रियासतों का भारत में विलय",
"7. संघ और राज्य क्षेत्र",
"8. राज्यों का पुनर्गठन",
"9. भारतीय नागरिकता",
"10. मौलिक अधिकार",
"11. राज्य के नीति निर्देशक सिद्धांत (DPSP)",
"12. मौलिक कर्तव्य",
"13. संघीय कार्यपालिका",
"14. संघीय संसद",
"15. भारत का महान्यायवादी (Attorney General of India)",
"16. भारत का नियंत्रक एवं महालेखा परीक्षक (CAG)",
"17. भारत की संचित निधि",
"18. भारत की आकस्मिकता निधि",
"19. संविधान में संशोधन",
"20. न्यायपालिका",
"21. राज्य की कार्यपालिका",
"22. केन्द्र-राज्य संबंध",
"23. अंतर्राज्य परिषद्",
"24. नीति आयोग",
"25. राष्ट्रीय विकास परिषद्",
"26. वित्त आयोग",
"27. लोक सेवा आयोग",
"28. निर्वाचन आयोग",
"29. परिसीमन आयोग",
"30. भारतीय राजव्यवस्था में वरीयता अनुक्रम (Order of Precedence)",
"31. राजभाषा",
"32. आपात उपबन्ध",
"33. जम्मू-कश्मीर को विशेष संवैधानिक दर्जा",
"34. भारत के राष्ट्रीय चिह्न",
"35. संसद की वित्तीय समितियाँ",
"36. पंचायती राज",
"37. महत्वपूर्ण शब्दावलियाँ",
"38. संविधान के कुछ महत्वपूर्ण अनुच्छेद",
"39. संविधान में किये गए प्रमुख संशोधन"
];

const COMPETITION_GEOGRAPHY = [
"1. भारत का भूगोल सामान्य जानकारी",
"2. भारत का भौतिक स्वरूप",
"3. भारत की नदियाँ",
"4. भारत की प्रमुख झीलें",
"5. भारत के प्रमुख जलप्रपात",
"6. भारत की जलवायु",
"7. भारत की मिट्टी",
"8. भारत की कृषि",
"9. भारत में सिंचाई",
"10. भारत के खनिज संसाधन",
"11. भारत के उद्योग",
"12. भारत में परिवहन",
"13. भारत की जनगणना 2011",
"14. भारत की प्रमुख बहुउद्देशीय नदी घाटी परियोजनाएँ",
"15. नदियों के किनारे बसे प्रमुख नगर",
"16. भारत के पर्वतीय नगर",
"17. भारत के प्रमुख वन्य जीव अभयारण्य/राष्ट्रीय उद्यान",
"18. भारत के बाघ अभयारण्य",
"19. भारत के प्रमुख भौगोलिक उपनाम",
"20. भारतीय राज्यों एवं केन्द्रशासित प्रदेशों की राजधानी",
"21. भारतीय जनजातियाँ"
];

const COMPETITION_HISTORY = [
"1. प्राचीन भारतीय इतिहास के स्रोत",
"2. प्रागैतिहासिक काल",
"3. सिंधु सभ्यता",
"4. वैदिक सभ्यता",
"5. महाजनपदों का उदय",
"6. जैन धर्म",
"7. बौद्ध धर्म",
"8. शैव धर्म",
"9. वैष्णव धर्म",
"10. इस्लाम धर्म",
"11. ईसाई धर्म",
"12. पारसी धर्म",
"13. मगध राज्य का उत्कर्ष",
"14. सिकंदर",
"15. मौर्य साम्राज्य",
"16. ब्राह्मण साम्राज्य",
"17. भारत के यवन राज्य",
"18. शक",
"19. कुषाण",
"20. संगम युग",
"21. गुप्त साम्राज्य",
"22. वाकाटक राजवंश",
"23. पुष्यभूति वंश या वर्द्धन वंश",
"24. दक्षिण भारत के प्रमुख राजवंश",
"25. सीमावर्ती राजवंशों का अभ्युदय",
"26. राजपूत राजवंशों की उत्पत्ति",
"27. भारत पर अरबों का आक्रमण",
"28. महमूद गजनवी",
"29. मुहम्मद गौरी",
"30. सल्तनत काल",
"31. विजयनगर साम्राज्य",
"32. बहमनी राज्य",
"33. स्वतंत्र प्रान्तीय राज्य",
"34. सूफी आन्दोलन",
"35. भक्ति आन्दोलन",
"36. मुगल साम्राज्य",
"37. मुगल शासन व्यवस्था",
"38. मराठों का उत्कर्ष",
"39. उत्तरकालीन मुगल सम्राट",
"40. भारत में यूरोपीय व्यापारिक कंपनियों का आगमन",
"41. बंगाल पर अंग्रेजों का आधिपत्य",
"42. अंग्रेजों के मैसूर से संबंध",
"43. सिक्ख एवं अंग्रेज",
"44. कंपनी के अधीन गवर्नर जेनरल",
"45. अंग्रेजी शासन के विरुद्ध महत्वपूर्ण विद्रोह",
"46. 1857 ई. की महान क्रांति",
"47. 1857 ई. की महान क्रांति के प्रमुख केंद्र",
"48. भारत का स्वतंत्रता संघर्ष: महत्वपूर्ण तथ्य",
"49. भारतीय धार्मिक, सामाजिक एवं राष्ट्रीय आन्दोलन से संबंधित महत्वपूर्ण संगठन एवं संस्थाएँ",
"50. भारतीय राष्ट्रीय आन्दोलन में संबंधित आन्दोलन एवं घटनाएँ",
"51. भारत के महान शहीद",
"52. भारतीय स्वतंत्रता आन्दोलन के प्रमुख वचन एवं नारे",
"53. स्वतंत्रता आंदोलन से संबंधित प्रकाशित पत्र, पत्रिकाएँ एवं पुस्तकें",
"54. उपाधि, प्राप्तकर्ता एवं दाता",
"55. कांग्रेस अधिवेशन: कब और कहाँ",
"56. ब्रिटिशकालीन आयोग/समितियाँ",
"57. भारतीय प्रेस का विकास",
"58. भारत की ऐतिहासिक लड़ाइयाँ",
"59. प्रमुख राजवंश, संस्थापक तथा राजधानी",
"60. सामाजिक सुधार अधिनियम",
"61. मुस्लिम सामाजिक धार्मिक आन्दोलन और संगठन"
];

const COMPETITION_PHYSICS = [
"1. मात्रक",
"2. गति",
"3. कार्य, ऊर्जा एवं शक्ति",
"4. गुरुत्वाकर्षण",
"5. दाब",
"6. प्लवन",
"7. पृष्ठ तनाव",
"8. श्यानता",
"9. प्रत्यास्थता",
"10. सरल आवर्त गति",
"11. तरंग",
"12. ध्वनि तरंग",
"13. ऊष्मा",
"14. प्रकाश",
"15. स्थिर वैद्युत",
"16. विद्युत् धारा",
"17. चुम्बकत्व",
"18. परमाणु भौतिकी",
"19. रेडियोसक्रियता",
"20. नाभिकीय विखंडन तथा संलयन",
"21. ब्रह्मांड"
];

const COMPETITION_CHEMISTRY = [
"1. पदार्थ एवं उसकी प्रकृति",
"2. परमाणु संरचना",
"3. गैसों का आचरण",
"4. तत्वों का आवर्ती वर्गीकरण",
"5. रासायनिक बंधन",
"6. ऑक्सीकरण एवं अवकरण",
"7. अम्ल, भस्म एवं लवण",
"8. विलयन",
"9. कार्बन एवं उसके यौगिक",
"10. ईंधन",
"11. धातुएँ",
"12. अधातुएँ",
"13. मिश्रधातु",
"14. मानव निर्मित पदार्थ",
"15. उत्प्रेरण"
];

const COMPETITION_BIOLOGY = [
"1. जीवधारियों का वर्गीकरण",
"2. कोशिका विज्ञान",
"3. जैव-विकास",
"4. आनुवंशिकी",
"5. वनस्पति विज्ञान",
"6. पारिस्थितिकी",
"7. प्रदूषण",
"8. प्राणी विज्ञान",
"9. मानव शरीर के तंत्र",
"10. पोषक पदार्थ",
"11. पोषण",
"12. मानव रोग",
"13. विविध",
"14. विज्ञान की कुछ प्रमुख शाखाएँ"
];

const COMPETITION_ECONOMICS = [
"1. अर्थशास्त्र और अर्थव्यवस्था",
"2. अर्थव्यवस्था के क्षेत्र",
"3. आर्थिक संवृद्धि एवं आर्थिक विकास",
"4. मानव विकास रिपोर्ट 2025",
"5. खुशहाली",
"6. विश्व खुशहाली रिपोर्ट-2025",
"7. विश्व खुशहाली रिपोर्ट-2025",
"8. वैश्विक लैंगिक अंतराल रिपोर्ट-2025",
"9. राष्ट्रीय आय",
"10. आर्थिक आयोजन",
"11. गरीबी",
"12. भारत में निर्धनता",
"13. नई आर्थिक नीति",
"14. भारतीय वित्त व्यवस्था",
"15. भारत में पत्र मुद्रा",
"16. भारत में प्रतिभूति-मुद्रण एवं सिक्कों का उत्पादन",
"17. टकसाल (Mints)",
"18. भारतीय प्रतिभूति एवं विनिमय बोर्ड (SEBI)",
"19. भारत के प्रमुख शेयर बाजार",
"20. भारत के प्रमुख शेयर मूल्य सूचकांक",
"21. बजट (Budget)",
"22. कर (Tax)",
"23. वस्तु एवं सेवाकर (Goods & Service Tax)",
"24. कृषि",
"25. उद्योग",
"26. विदेशी व्यापार एवं भुगतान संतुलन",
"27. अर्थशास्त्र : परीक्षोपयोगी तथ्य",
"28. महत्वपूर्ण आर्थिक शब्दावली"
];



const COMPETITION_LUCENT = [
...COMPETITION_HISTORY,
...COMPETITION_GEOGRAPHY,
...COMPETITION_POLITY,
...COMPETITION_ECONOMICS,
...COMPETITION_PHYSICS,
...COMPETITION_CHEMISTRY,
...COMPETITION_BIOLOGY
];

const COMPETITION_SPEEDY_SCIENCE = COMPETITION_PHYSICS.concat(COMPETITION_CHEMISTRY).concat(COMPETITION_BIOLOGY);
const COMPETITION_SPEEDY_SOCIAL = COMPETITION_HISTORY.concat(COMPETITION_GEOGRAPHY).concat(COMPETITION_POLITY).concat(COMPETITION_ECONOMICS);
const COMPETITION_SAR_SANGRAH = COMPETITION_LUCENT;
export const COMPETITION_DATA: Record<string, string[]> = {
    // CBSE Mappings
    "CBSE-COMPETITION-Political Science": COMPETITION_POLITY,
    "CBSE-COMPETITION-Geography": COMPETITION_GEOGRAPHY,
    "CBSE-COMPETITION-History": COMPETITION_HISTORY,
    "CBSE-COMPETITION-Physics": COMPETITION_PHYSICS,
    "CBSE-COMPETITION-Chemistry": COMPETITION_CHEMISTRY,
    "CBSE-COMPETITION-Biology": COMPETITION_BIOLOGY,
    "CBSE-COMPETITION-Economics": COMPETITION_ECONOMICS,
    "CBSE-COMPETITION-Lucent GK": COMPETITION_LUCENT,
    "CBSE-COMPETITION-Speedy Science": COMPETITION_SPEEDY_SCIENCE,
    "CBSE-COMPETITION-Speedy Social Science": COMPETITION_SPEEDY_SOCIAL,
    "CBSE-COMPETITION-Sar Sangrah MCQ": COMPETITION_SAR_SANGRAH,

    // BSEB Mappings
    "BSEB-COMPETITION-Political Science": COMPETITION_POLITY,
    "BSEB-COMPETITION-Geography": COMPETITION_GEOGRAPHY,
    "BSEB-COMPETITION-History": COMPETITION_HISTORY,
    "BSEB-COMPETITION-Physics": COMPETITION_PHYSICS,
    "BSEB-COMPETITION-Chemistry": COMPETITION_CHEMISTRY,
    "BSEB-COMPETITION-Biology": COMPETITION_BIOLOGY,
    "BSEB-COMPETITION-Economics": COMPETITION_ECONOMICS,
    "BSEB-COMPETITION-Lucent GK": COMPETITION_LUCENT,
    "BSEB-COMPETITION-Speedy Science": COMPETITION_SPEEDY_SCIENCE,
    "BSEB-COMPETITION-Speedy Social Science": COMPETITION_SPEEDY_SOCIAL,
    "BSEB-COMPETITION-Sar Sangrah MCQ": COMPETITION_SAR_SANGRAH,

    // Fallback / Generic (Optional, if we ever switch to generic board key)
    "COMPETITION-COMPETITION-Political Science": COMPETITION_POLITY,
    "COMPETITION-COMPETITION-Geography": COMPETITION_GEOGRAPHY,
    "COMPETITION-COMPETITION-History": COMPETITION_HISTORY,
    "COMPETITION-COMPETITION-Physics": COMPETITION_PHYSICS,
    "COMPETITION-COMPETITION-Chemistry": COMPETITION_CHEMISTRY,
    "COMPETITION-COMPETITION-Biology": COMPETITION_BIOLOGY,
    "COMPETITION-COMPETITION-Economics": COMPETITION_ECONOMICS,
    "COMPETITION-COMPETITION-Lucent GK": COMPETITION_LUCENT,
    "COMPETITION-COMPETITION-Speedy Science": COMPETITION_SPEEDY_SCIENCE,
    "COMPETITION-COMPETITION-Speedy Social Science": COMPETITION_SPEEDY_SOCIAL,
    "COMPETITION-COMPETITION-Sar Sangrah MCQ": COMPETITION_SAR_SANGRAH,
};
