export const FULL_SYLLABUS: Record<string, string[]> = {
  "BSEB-10-Mathematics": [
    "वास्तविक संख्याएँ",
    "बहुपद",
    "दो चर वाले रैखिक समीकरण युग्म",
    "द्विघात समीकरण",
    "समांतर श्रेढियाँ",
    "त्रिभुज",
    "निर्देशांक ज्यामिति",
    "त्रिकोणमिति का परिचय",
    "त्रिकोणमिति के कुछ अनुप्रयोग",
    "वृत्त",
    "रचनाएँ",
    "वृत्तों से संबंधित क्षेत्रफल",
    "पृष्ठीय क्षेत्रफल और आयतन",
    "सांख्यिकी",
    "प्रायिकता"
  ],
  "BSEB-10-Physics": [
    "प्रकाश-परावर्तन तथा अपवर्तन",
    "मानव नेत्र तथा रंगबिरंगा संसार",
    "विद्युत",
    "विद्युत धारा के चुंबकीय प्रभाव",
    "ऊर्जा के स्रोत"
  ],
  "BSEB-10-Chemistry": [
    "रासायनिक अभिक्रियाएँ एवं समीकरण",
    "अम्ल, क्षारक एवं लवण",
    "धातु एवं अधातु",
    "कार्बन एवं उसके यौगिक",
    "तत्वों का आवर्त वर्गीकरण"
  ],
  "BSEB-10-Biology": [
    "जैव प्रक्रम",
    "नियंत्रण एवं समन्वय",
    "जीव जनन कैसे करते हैं",
    "आनुवंशिकता एवं जैव विकास",
    "हमारा पर्यावरण",
    "प्राकृतिक संसाधनों का प्रबंधन"
  ],
  "BSEB-10-Science": [
    "रासायनिक अभिक्रियाएँ एवं समीकरण",
    "अम्ल, क्षारक एवं लवण",
    "धातु एवं अधातु",
    "कार्बन एवं उसके यौगिक",
    "तत्वों का आवर्त वर्गीकरण",
    "जैव प्रक्रम",
    "नियंत्रण एवं समन्वय",
    "जीव जनन कैसे करते हैं?",
    "आनुवंशिकता एवं जैव विकास",
    "प्रकाश – परावर्तन तथा अपवर्तन",
    "मानव नेत्र तथा रंगबिरंगा संसार",
    "विद्युत",
    "विद्युत धारा के चुंबकीय प्रभाव",
    "ऊर्जा के स्रोत",
    "हमारा पर्यावरण",
    "प्राकृतिक संसाधनों का संपोषित प्रबंधन"
  ],

  "BSEB-9-History": [
    "भौगोलिक खोजें",
    "अमेरिकी स्वतंत्रता संग्राम",
    "फ्रांस की क्रांति",
    "विश्व युद्धों का इतिहास",
    "नाजीवाद",
    "वन्य समाज और उपनिवेशवाद",
    "शान्ति के प्रयास",
    "कृषि और खेतिहर समाज"
  ],
  "BSEB-9-Geography": [
    "स्थिति एवं विस्तार",
    "भौतिक स्वरूप : संरचना एवं उच्चावच",
    "अपवाह स्वरूप",
    "जलवायु",
    "प्राकृतिक वनस्पति एवं वन्य प्राणी",
    "जनसंख्या",
    "भारत के पड़ोसी देश",
    "मानचित्र अध्ययन",
    "क्षेत्रीय अध्ययन",
    "आपदा प्रबंधन : एक परिचय",
    "मानवीय गलतियों के कारण घटित आपदाएँ : नाभिकीय, जैविक और रासायनिक",
    "सामान्य आपदाएँ : निवारण एवं नियंत्रण",
    "समुदाय आधारित आपदा प्रबंधन"
  ],
  "BSEB-9-Political Science": [
    "लोकतंत्र का क्रमिक विकास",
    "लोकतंत्र क्या और क्यों?",
    "संविधान निर्माण",
    "चुनावी राजनीति",
    "संसदीय लोकतंत्र की संस्थाएँ",
    "लोकतांत्रिक अधिकार"
  ],
  "BSEB-9-Economics": [
    "बिहार के एक गाँव की आर्थिक कहानी",
    "मानव संसाधन",
    "गरीबी",
    "बेरोजगारी",
    "कृषि एवं खाद्यान्न सुरक्षा",
    "कृषि मजदूरों की समस्याएँ"
  ],
  "BSEB-10-History": [
    "यूरोप में राष्ट्रवाद",
    "समाजवाद एवं साम्यवाद",
    "हिन्द-चीन में राष्ट्रवादी आन्दोलन",
    "भारत में राष्ट्रवाद",
    "अर्थव्यवस्था और आजीविका",
    "शहरीकरण एवं शहरी जीवन",
    "व्यापार और भूमंडलीकरण",
    "प्रेस-संस्कृति एवं राष्ट्रवाद"
  ],
  "BSEB-10-Geography": [
    "संसाधन, विकास और उपयोग",
    "भूमि और मृदा संसाधन",
    "जल संसाधन",
    "वन और वन्य प्राणी संसाधन",
    "खनिज संसाधन",
    "ऊर्जा या शक्ति संसाधन",
    "कृषि संसाधन",
    "निर्माण उद्योग",
    "परिवहन, संचार और व्यापार",
    "बिहार - संसाधन एवं उपयोग",
    "मानचित्र-अध्ययन (उच्चावच प्रदर्शन)",
    "प्राकृतिक संकट और आपदा",
    "आपदा प्रबंधन"
  ],
  "BSEB-10-Political Science": [
    "लोकतंत्र में सत्ता की साझेदारी",
    "सत्ता में साझेदारी की कार्यप्रणाली",
    "लोकतंत्र में प्रतिस्पर्धा एवं संघर्ष",
    "लोकतंत्र की उपलब्धियाँ",
    "लोकतंत्र की चुनौतियों"
  ],
  "BSEB-10-Economics": [
    "अर्थव्यवस्था एवं इसके विकास का इतिहास",
    "राज्य एवं राष्ट्र की आय",
    "मुद्रा, बचत एवं साख",
    "हमारी वित्तीय संस्थाएँ",
    "रोजगार एवं सेवाएँ",
    "वैश्वीकरण",
    "उपभोक्ता जागरण एवं संरक्षण"
  ],
"BSEB-10-Social Science": [
    "यूरोप में राष्ट्रवाद",
    "समाजवाद एवं साम्यवाद",
    "हिन्द-चीन में राष्ट्रवादी आंदोलन",
    "भारत में राष्ट्रवाद",
    "अर्थव्यवस्था और आजीविका",
    "शहरीकरण एवं शहरी जीवन",
    "व्यापार और भूमंडलीकरण",
    "प्रेस-संस्कृति एवं राष्ट्रवाद",
    "भारत: संसाधन एवं उपयोग",
    "कृषि",
    "निर्माण उद्योग",
    "परिवहन, संचार एवं व्यापार",
    "बिहार: कृषि एवं वन संसाधन",
    "मानचित्र अध्ययन",
    "लोकतंत्र में सत्ता की साझेदारी",
    "लोकतंत्र की चुनौतियाँ",
    "अर्थव्यवस्था एवं इसके विकास का इतिहास",
    "मुद्रा, बचत एवं साख",
    "वैश्वीकरण",
    "उपभोक्ता जागरण एवं संरक्षण",
    "आपदा प्रबंधन"
  ],
  "BSEB-11-Biology": [
    "The Living World",
    "Biological Classification",
    "Plant Kingdom",
    "Animal Kingdom",
    "Morphology of Flowering Plants",
    "Anatomy of Flowering Plants",
    "Structural Organisation in Animals",
    "Cell: The Unit of Life",
    "Biomolecules",
    "Cell Cycle and Cell Division",
    "Transport in Plants",
    "Mineral Nutrition",
    "Photosynthesis in Higher Plants",
    "Respiration in Plants",
    "Plant Growth and Development",
    "Digestion and Absorption",
    "Breathing and Exchange of Gases",
    "Body Fluids and Circulation",
    "Excretory Products and their Elimination",
    "Locomotion and Movement",
    "Neural Control and Coordination",
    "Chemical Coordination and Integration"
  ],
  "BSEB-11-Chemistry": [
    "Some Basic Concepts of Chemistry",
    "Structure of Atom",
    "Classification of Elements and Periodicity in Properties",
    "Chemical Bonding and Molecular Structure",
    "States of Matter",
    "Thermodynamics",
    "Equilibrium",
    "Redox Reactions",
    "Hydrogen",
    "The s-Block Elements",
    "The p-Block Elements",
    "Organic Chemistry – Some Basic Principles and Techniques",
    "Hydrocarbons",
    "Environmental Chemistry"
  ],
  "BSEB-11-Mathematics": [
    "Sets",
    "Relations and Functions",
    "Trigonometric Functions",
    "Principle of Mathematical Induction",
    "Complex Numbers and Quadratic Equations",
    "Linear Inequalities",
    "Permutations and Combinations",
    "Binomial Theorem",
    "Sequences and Series",
    "Straight Lines",
    "Conic Sections",
    "Introduction to Three Dimensional Geometry",
    "Limits and Derivatives",
    "Mathematical Reasoning",
    "Statistics",
    "Probability"
  ],
  "BSEB-11-Physics": [
    "Physical World",
    "Units and Measurements",
    "Motion in a Straight Line",
    "Motion in a Plane",
    "Laws of Motion",
    "Work, Energy and Power",
    "System of Particles and Rotational Motion",
    "Gravitation",
    "Mechanical Properties of Solids",
    "Mechanical Properties of Fluids",
    "Thermal Properties of Matter",
    "Thermodynamics",
    "Kinetic Theory",
    "Oscillations",
    "Waves"
  ],
  "BSEB-12-Biology": [
    "Reproduction in Organisms",
    "Sexual Reproduction in Flowering Plants",
    "Human Reproduction",
    "Reproductive Health",
    "Principles of Inheritance and Variation",
    "Molecular Basis of Inheritance",
    "Evolution",
    "Human Health and Disease",
    "Strategies for Enhancement in Food Production",
    "Microbes in Human Welfare",
    "Biotechnology: Principles and Processes",
    "Biotechnology and its Applications",
    "Organisms and Populations",
    "Ecosystem",
    "Biodiversity and Conservation",
    "Environmental Issues"
  ],
  "BSEB-12-Chemistry": [
    "The Solid State",
    "Solutions",
    "Electrochemistry",
    "Chemical Kinetics",
    "Surface Chemistry",
    "General Principles and Processes of Isolation of Elements",
    "The p-Block Elements",
    "The d- and f- Block Elements",
    "Coordination Compounds",
    "Haloalkanes and Haloarenes",
    "Alcohols, Phenols and Ethers",
    "Aldehydes, Ketones and Carboxylic Acids",
    "Amines",
    "Biomolecules",
    "Polymers",
    "Chemistry in Everyday Life"
  ],
  "BSEB-12-Mathematics": [
    "Relations and Functions",
    "Inverse Trigonometric Functions",
    "Matrices",
    "Determinants",
    "Continuity and Differentiability",
    "Application of Derivatives",
    "Integrals",
    "Application of Integrals",
    "Differential Equations",
    "Vector Algebra",
    "Three Dimensional Geometry",
    "Linear Programming",
    "Probability"
  ],
  "BSEB-12-Physics": [
    "Electric Charges and Fields",
    "Electrostatic Potential and Capacitance",
    "Current Electricity",
    "Moving Charges and Magnetism",
    "Magnetism and Matter",
    "Electromagnetic Induction",
    "Alternating Current",
    "Electromagnetic Waves",
    "Ray Optics and Optical Instruments",
    "Wave Optics",
    "Dual Nature of Radiation and Matter",
    "Atoms",
    "Nuclei",
    "Semiconductor Electronics",
    "Communication Systems"
  ],
  "BSEB-6-Mathematics": [
    "Knowing Our Numbers",
    "Whole Numbers",
    "Playing with Numbers",
    "Basic Geometrical Ideas",
    "Understanding Elementary Shapes",
    "Integers",
    "Fractions",
    "Decimals",
    "Data Handling",
    "Mensuration",
    "Algebra",
    "Ratio and Proportion",
    "Symmetry",
    "Practical Geometry"
  ],
  "BSEB-6-Science": [
    "Food: Where Does It Come From?",
    "Components of Food",
    "Fibre to Fabric",
    "Sorting Materials into Groups",
    "Separation of Substances",
    "Changes Around Us",
    "Getting to Know Plants",
    "Body Movements",
    "The Living Organisms and Their Surroundings",
    "Motion and Measurement of Distances",
    "Light, Shadows and Reflections",
    "Electricity and Circuits",
    "Fun with Magnets",
    "Water",
    "Air Around Us",
    "Garbage In, Garbage Out"
  ],
  "BSEB-6-History": [
    "What, Where, How and When?",
    "From Hunting–Gathering to Growing Food",
    "In the Earliest Cities",
    "What Books and Burials Tell Us",
    "Kingdoms, Kings and an Early Republic",
    "New Questions and Ideas",
    "Ashoka, The Emperor Who Gave Up War",
    "Vital Villages, Thriving Towns",
    "Traders, Kings and Pilgrims",
    "New Empires and Kingdoms",
    "Buildings, Paintings and Books"
  ],
  "BSEB-6-Geography": [
    "The Earth in the Solar System",
    "Globe: Latitudes and Longitudes",
    "Motions of the Earth",
    "Maps",
    "Major Domains of the Earth",
    "Major Landforms of the Earth",
    "Our Country – India",
    "India: Climate, Vegetation and Wildlife"
  ],
  "BSEB-6-Political Science": [
    "Understanding Diversity",
    "Diversity and Discrimination",
    "What is Government?",
    "Key Elements of a Democratic Government",
    "Panchayati Raj",
    "Rural Administration",
    "Urban Administration",
    "Rural Livelihoods",
    "Urban Livelihoods"
  ],
  "BSEB-6-Social Science": [
    "What, Where, How and When?",
    "From Hunting–Gathering to Growing Food",
    "In the Earliest Cities",
    "What Books and Burials Tell Us",
    "Kingdoms, Kings and an Early Republic",
    "New Questions and Ideas",
    "Ashoka, The Emperor Who Gave Up War",
    "Vital Villages, Thriving Towns",
    "Traders, Kings and Pilgrims",
    "New Empires and Kingdoms",
    "Buildings, Paintings and Books",
    "The Earth in the Solar System",
    "Globe: Latitudes and Longitudes",
    "Motions of the Earth",
    "Maps",
    "Major Domains of the Earth",
    "Major Landforms of the Earth",
    "Our Country – India",
    "India: Climate, Vegetation and Wildlife"
  ],
  "BSEB-7-Mathematics": [
    "Integers",
    "Fractions and Decimals",
    "Data Handling",
    "Simple Equations",
    "Lines and Angles",
    "The Triangle and its Properties",
    "Congruence of Triangles",
    "Comparing Quantities",
    "Rational Numbers",
    "Practical Geometry",
    "Perimeter and Area",
    "Algebraic Expressions",
    "Exponents and Powers",
    "Symmetry",
    "Visualising Solid Shapes"
  ],
  "BSEB-7-Science": [
    "Nutrition in Plants",
    "Nutrition in Animals",
    "Fibre to Fabric",
    "Heat",
    "Acids, Bases and Salts",
    "Physical and Chemical Changes",
    "Weather, Climate and Adaptations",
    "Winds, Storms and Cyclones",
    "Soil",
    "Respiration in Organisms",
    "Transportation in Animals and Plants",
    "Reproduction in Plants",
    "Motion and Time",
    "Electric Current and its Effects",
    "Light",
    "Water: A Precious Resource",
    "Forests: Our Lifeline",
    "Wastewater Story"
  ],
  "BSEB-7-History": [
    "Tracing Changes Through a Thousand Years",
    "New Kings and Kingdoms",
    "The Delhi Sultans",
    "The Mughal Empire",
    "Rulers and Buildings",
    "Towns, Traders and Craftspersons",
    "Tribes, Nomads and Settled Communities",
    "Devotional Paths to the Divine",
    "The Making of Regional Cultures",
    "Eighteenth-Century Political Formations"
  ],
  "BSEB-7-Geography": [
    "Environment",
    "Inside Our Earth",
    "Our Changing Earth",
    "Air",
    "Water",
    "Natural Vegetation and Wildlife"
  ],
  "BSEB-7-Political Science": [
    "Equality",
    "Role of the Government in Health",
    "How the State Government Works",
    "Growing up as Boys and Girls",
    "Women Change the World",
    "Understanding Media",
    "Markets Around Us",
    "A Shirt in the Market"
  ],
  "BSEB-7-Social Science": [
    "Tracing Changes Through a Thousand Years",
    "New Kings and Kingdoms",
    "The Delhi Sultans",
    "The Mughal Empire",
    "Rulers and Buildings",
    "Towns, Traders and Craftspersons",
    "Tribes, Nomads and Settled Communities",
    "Devotional Paths to the Divine",
    "The Making of Regional Cultures",
    "Eighteenth-Century Political Formations",
    "Environment",
    "Inside Our Earth",
    "Our Changing Earth",
    "Air",
    "Water",
    "Natural Vegetation and Wildlife"
  ],
  "BSEB-8-Mathematics": [
    "Rational Numbers",
    "Linear Equations in One Variable",
    "Understanding Quadrilaterals",
    "Practical Geometry",
    "Data Handling",
    "Squares and Square Roots",
    "Cubes and Cube Roots",
    "Comparing Quantities",
    "Algebraic Expressions and Identities",
    "Visualising Solid Shapes",
    "Mensuration",
    "Exponents and Powers",
    "Direct and Inverse Proportions",
    "Factorisation",
    "Introduction to Graphs",
    "Playing with Numbers"
  ],
  "BSEB-8-Science": [
    "Crop Production and Management",
    "Microorganisms: Friend and Foe",
    "Synthetic Fibres and Plastics",
    "Materials: Metals and Non-Metals",
    "Coal and Petroleum",
    "Combustion and Flame",
    "Conservation of Plants and Animals",
    "Cell - Structure and Functions",
    "Reproduction in Animals",
    "Reaching the Age of Adolescence",
    "Force and Pressure",
    "Friction",
    "Sound",
    "Chemical Effects of Electric Current",
    "Some Natural Phenomena",
    "Light",
    "Stars and The Solar System",
    "Pollution of Air and Water"
  ],
  "BSEB-8-History": [
    "How, When and Where",
    "From Trade to Territory",
    "Ruling the Countryside",
    "Tribals, Dikus and the Vision of a Golden Age",
    "When People Rebel",
    "Weavers, Iron Smelters and Factory Owners",
    "Civilising the 'Native', Educating the Nation",
    "Women, Caste and Reform",
    "The Making of the National Movement",
    "India After Independence"
  ],
  "BSEB-8-Geography": [
    "Resources",
    "Land, Soil, Water, Natural Vegetation and Wildlife",
    "Mineral and Power Resources",
    "Agriculture",
    "Industries",
    "Human Resources"
  ],
  "BSEB-8-Political Science": [
    "The Indian Constitution",
    "Understanding Secularism"
  ],
  "BSEB-8-Social Science": [
    "How, When and Where",
    "From Trade to Territory",
    "Ruling the Countryside",
    "Tribals, Dikus and the Vision of a Golden Age",
    "When People Rebel",
    "Weavers, Iron Smelters and Factory Owners",
    "Civilising the 'Native', Educating the Nation",
    "Women, Caste and Reform",
    "The Making of the National Movement",
    "India After Independence",
    "Resources",
    "Land, Soil, Water, Natural Vegetation and Wildlife",
    "Mineral and Power Resources",
    "Agriculture",
    "Industries",
    "Human Resources",
    "The Indian Constitution",
    "Understanding Secularism"
  ],
  "BSEB-9-Mathematics": [
    "संख्या पद्धति",
    "बहुपद",
    "निर्देशांक ज्यामिति",
    "दो चरों वाले रैखिक समीकरण",
    "यूक्लिड की ज्यामिति का परिचय",
    "रेखाएँ और कोण",
    "त्रिभुज",
    "चतुर्भुज",
    "समांतर चतुर्भुजों और त्रिभुजों के क्षेत्रफल",
    "वृत्त",
    "रचनाएँ",
    "हीरोन का सूत्र",
    "पृष्ठीय क्षेत्रफल और आयतन",
    "सांख्यिकी",
    "प्रायिकता"
  ],
  "BSEB-9-Physics": [
    "गति",
    "बल तथा गति के नियम",
    "गुरुत्वाकर्षण",
    "कार्य तथा ऊर्जा",
    "ध्वनि"
  ],
  "BSEB-9-Chemistry": [
    "हमारे आस-पास के पदार्थ",
    "क्या हमारे आस-पास के पदार्थ शुद्ध हैं",
    "परमाणु एवं अणु",
    "परमाणु की संरचना"
  ],
  "BSEB-9-Biology": [
    "जीवन की मौलिक इकाई",
    "ऊतक",
    "जीवों में विविधता",
    "हम बीमार क्यों होते हैं",
    "प्राकृतिक संपदा",
    "खाद्य संसाधनों में सुधार"
  ],
  "BSEB-9-Science": [
    "हमारे आस-पास के पदार्थ",
    "क्या हमारे आस-पास के पदार्थ शुद्ध हैं",
    "परमाणु एवं अणु",
    "परमाणु की संरचना",
    "जीवन की मौलिक इकाई",
    "ऊतक",
    "जीवों में विविधता",
    "गति",
    "बल तथा गति के नियम",
    "गुरुत्वाकर्षण",
    "कार्य तथा ऊर्जा",
    "ध्वनि",
    "हम बीमार क्यों होते हैं",
    "प्राकृतिक संपदा",
    "खाद्य संसाधनों में सुधार"
  ],
  "BSEB-9-Social Science": [
    "भौगोलिक खोजें",
    "अमेरिकी स्वतंत्रता संग्राम",
    "फ्रांस की क्रांति",
    "विश्वयुद्धों का इतिहास",
    "नाजीवाद",
    "वन्य समाज और उपनिवेशवाद",
    "शांति के प्रयास",
    "कृषि और खेतिहर समाज",
    "स्थिति और विस्तार",
    "भौतिक स्वरूप: संरचना और उच्चावच",
    "अपवाह स्वरूप",
    "जलवायु",
    "प्राकृतिक वनस्पति एवं वन्य प्राणी",
    "जनसंख्या",
    "लोकतंत्र का क्रमिक विकास",
    "संविधान निर्माण",
    "चुनावी राजनीति",
    "संसदीय लोकतंत्र की संस्थाएँ",
    "लोकतांत्रिक अधिकार",
    "बिहार के एक गाँव की कहानी",
    "मानव एक संसाधन",
    "गरीबी: एक चुनौती",
    "भारत में खाद्य सुरक्षा"
  ],
  "BSEB-COMPETITION-Biology": [
    "जीवधारियों का वर्गीकरण",
    "कोशिका विज्ञान",
    "जैव-विकास",
    "आनुवंशिकी",
    "वनस्पति विज्ञान",
    "पारिस्थितिकी",
    "प्रदूषण",
    "प्राणी विज्ञान",
    "मानव शरीर के तंत्र",
    "पोषक पदार्थ",
    "पोषण",
    "मानव रोग",
    "विविध",
    "विज्ञान की कुछ प्रमुख शाखाएँ"
  ],
  "BSEB-COMPETITION-Chemistry": [
    "पदार्थ एवं उसकी प्रकृति",
    "परमाणु संरचना",
    "गैसों का आचरण",
    "तत्वों का आवर्ती वर्गीकरण",
    "रासायनिक बंधन",
    "ऑक्सीकरण एवं अवकरण",
    "अम्ल, भस्म एवं लवण",
    "विलयन",
    "कार्बन एवं उसके यौगिक",
    "ईंधन",
    "धातुएँ",
    "अधातुएँ",
    "मिश्रधातु",
    "मानव निर्मित पदार्थ",
    "उत्प्रेरण"
  ],
  "BSEB-COMPETITION-Economics": [
    "अर्थशास्त्र और अर्थव्यवस्था",
    "अर्थव्यवस्था के क्षेत्र",
    "आर्थिक संवृद्धि एवं आर्थिक विकास",
    "मानव विकास रिपोर्ट 2025",
    "खुशहाली",
    "विश्व खुशहाली रिपोर्ट-2025",
    "विश्व खुशहाली रिपोर्ट-2025",
    "वैश्विक लैंगिक अंतराल रिपोर्ट-2025",
    "राष्ट्रीय आय",
    "आर्थिक आयोजन",
    "गरीबी",
    "भारत में निर्धनता",
    "नई आर्थिक नीति",
    "भारतीय वित्त व्यवस्था",
    "भारत में पत्र मुद्रा",
    "भारत में प्रतिभूति-मुद्रण एवं सिक्कों का उत्पादन",
    "टकसाल (Mints)",
    "भारतीय प्रतिभूति एवं विनिमय बोर्ड (SEBI)",
    "भारत के प्रमुख शेयर बाजार",
    "भारत के प्रमुख शेयर मूल्य सूचकांक",
    "बजट (Budget)",
    "कर (Tax)",
    "वस्तु एवं सेवाकर (Goods & Service Tax)",
    "कृषि",
    "उद्योग",
    "विदेशी व्यापार एवं भुगतान संतुलन",
    "अर्थशास्त्र : परीक्षोपयोगी तथ्य",
    "महत्वपूर्ण आर्थिक शब्दावली"
  ],
  "BSEB-COMPETITION-Geography": [
    "भारत का भूगोल सामान्य जानकारी",
    "भारत का भौतिक स्वरूप",
    "भारत की नदियाँ",
    "भारत की प्रमुख झीलें",
    "भारत के प्रमुख जलप्रपात",
    "भारत की जलवायु",
    "भारत की मिट्टी",
    "भारत की कृषि",
    "भारत में सिंचाई",
    "भारत के खनिज संसाधन",
    "भारत के उद्योग",
    "भारत में परिवहन",
    "भारत की जनगणना 2011",
    "भारत की प्रमुख बहुउद्देशीय नदी घाटी परियोजनाएँ",
    "नदियों के किनारे बसे प्रमुख नगर",
    "भारत के पर्वतीय नगर",
    "भारत के प्रमुख वन्य जीव अभयारण्य/राष्ट्रीय उद्यान",
    "भारत के बाघ अभयारण्य",
    "भारत के प्रमुख भौगोलिक उपनाम",
    "भारतीय राज्यों एवं केन्द्रशासित प्रदेशों की राजधानी",
    "भारतीय जनजातियाँ"
  ],
  "BSEB-COMPETITION-History": [
    "प्राचीन भारतीय इतिहास के स्रोत",
    "प्रागैतिहासिक काल",
    "सिंधु सभ्यता",
    "वैदिक सभ्यता",
    "महाजनपदों का उदय",
    "जैन धर्म",
    "बौद्ध धर्म",
    "शैव धर्म",
    "वैष्णव धर्म",
    "इस्लाम धर्म",
    "ईसाई धर्म",
    "पारसी धर्म",
    "मगध राज्य का उत्कर्ष",
    "सिकंदर",
    "मौर्य साम्राज्य",
    "ब्राह्मण साम्राज्य",
    "भारत के यवन राज्य",
    "शक",
    "कुषाण",
    "संगम युग",
    "गुप्त साम्राज्य",
    "वाकाटक राजवंश",
    "पुष्यभूति वंश या वर्द्धन वंश",
    "दक्षिण भारत के प्रमुख राजवंश",
    "सीमावर्ती राजवंशों का अभ्युदय",
    "राजपूत राजवंशों की उत्पत्ति",
    "भारत पर अरबों का आक्रमण",
    "महमूद गजनवी",
    "मुहम्मद गौरी",
    "सल्तनत काल",
    "विजयनगर साम्राज्य",
    "बहमनी राज्य",
    "स्वतंत्र प्रान्तीय राज्य",
    "सूफी आन्दोलन",
    "भक्ति आन्दोलन",
    "मुगल साम्राज्य",
    "मुगल शासन व्यवस्था",
    "मराठों का उत्कर्ष",
    "उत्तरकालीन मुगल सम्राट",
    "भारत में यूरोपीय व्यापारिक कंपनियों का आगमन",
    "बंगाल पर अंग्रेजों का आधिपत्य",
    "अंग्रेजों के मैसूर से संबंध",
    "सिक्ख एवं अंग्रेज",
    "कंपनी के अधीन गवर्नर जेनरल",
    "अंग्रेजी शासन के विरुद्ध महत्वपूर्ण विद्रोह",
    "1857 ई. की महान क्रांति",
    "1857 ई. की महान क्रांति के प्रमुख केंद्र",
    "भारत का स्वतंत्रता संघर्ष: महत्वपूर्ण तथ्य",
    "भारतीय धार्मिक, सामाजिक एवं राष्ट्रीय आन्दोलन से संबंधित महत्वपूर्ण संगठन एवं संस्थाएँ",
    "भारतीय राष्ट्रीय आन्दोलन में संबंधित आन्दोलन एवं घटनाएँ",
    "भारत के महान शहीद",
    "भारतीय स्वतंत्रता आन्दोलन के प्रमुख वचन एवं नारे",
    "स्वतंत्रता आंदोलन से संबंधित प्रकाशित पत्र, पत्रिकाएँ एवं पुस्तकें",
    "उपाधि, प्राप्तकर्ता एवं दाता",
    "कांग्रेस अधिवेशन: कब और कहाँ",
    "ब्रिटिशकालीन आयोग/समितियाँ",
    "भारतीय प्रेस का विकास",
    "भारत की ऐतिहासिक लड़ाइयाँ",
    "प्रमुख राजवंश, संस्थापक तथा राजधानी",
    "सामाजिक सुधार अधिनियम",
    "मुस्लिम सामाजिक धार्मिक आन्दोलन और संगठन"
  ],
  "BSEB-COMPETITION-Physics": [
    "मात्रक",
    "गति",
    "कार्य, ऊर्जा एवं शक्ति",
    "गुरुत्वाकर्षण",
    "दाब",
    "प्लवन",
    "पृष्ठ तनाव",
    "श्यानता",
    "प्रत्यास्थता",
    "सरल आवर्त गति",
    "तरंग",
    "ध्वनि तरंग",
    "ऊष्मा",
    "प्रकाश",
    "स्थिर वैद्युत",
    "विद्युत् धारा",
    "चुम्बकत्व",
    "परमाणु भौतिकी",
    "रेडियोसक्रियता",
    "नाभिकीय विखंडन तथा संलयन",
    "ब्रह्मांड"
  ],
  "BSEB-COMPETITION-Political Science": [
    "भारतीय संविधान के विकास का संक्षिप्त इतिहास",
    "भारतीय संविधान सभा",
    "भारतीय संविधान की उद्देशिका अथवा प्रस्तावना",
    "भारतीय संविधान के विदेशी स्रोत",
    "भारतीय संविधान की अनुसूची",
    "देशी रियासतों का भारत में विलय",
    "संघ और राज्य क्षेत्र",
    "राज्यों का पुनर्गठन",
    "भारतीय नागरिकता",
    "मौलिक अधिकार",
    "राज्य के नीति निर्देशक सिद्धांत (DPSP)",
    "मौलिक कर्तव्य",
    "संघीय कार्यपालिका",
    "संघीय संसद",
    "भारत का महान्यायवादी (Attorney General of India)",
    "भारत का नियंत्रक एवं महालेखा परीक्षक (CAG)",
    "भारत की संचित निधि",
    "भारत की आकस्मिकता निधि",
    "संविधान में संशोधन",
    "न्यायपालिका",
    "राज्य की कार्यपालिका",
    "केन्द्र-राज्य संबंध",
    "अंतर्राज्य परिषद्",
    "नीति आयोग",
    "राष्ट्रीय विकास परिषद्",
    "वित्त आयोग",
    "लोक सेवा आयोग",
    "निर्वाचन आयोग",
    "परिसीमन आयोग",
    "भारतीय राजव्यवस्था में वरीयता अनुक्रम (Order of Precedence)",
    "राजभाषा",
    "आपात उपबन्ध",
    "जम्मू-कश्मीर को विशेष संवैधानिक दर्जा",
    "भारत के राष्ट्रीय चिह्न",
    "संसद की वित्तीय समितियाँ",
    "पंचायती राज",
    "महत्वपूर्ण शब्दावलियाँ",
    "संविधान के कुछ महत्वपूर्ण अनुच्छेद",
    "संविधान में किये गए प्रमुख संशोधन"
  ],
  "CBSE-10-Mathematics": [
    "Real Numbers",
    "Polynomials",
    "Pair of Linear Equations in Two Variables",
    "Quadratic Equations",
    "Arithmetic Progressions",
    "Triangles",
    "Coordinate Geometry",
    "Introduction to Trigonometry",
    "Some Applications of Trigonometry",
    "Circles",
    "Areas Related to Circles",
    "Surface Areas and Volumes",
    "Statistics",
    "Probability"
  ],
  "CBSE-10-Physics": [
    "Light – Reflection and Refraction",
    "The Human Eye and the Colourful World",
    "Electricity",
    "Magnetic Effects of Electric Current"
  ],
  "CBSE-10-Chemistry": [
    "Chemical Reactions and Equations",
    "Acids, Bases and Salts",
    "Metals and Non-Metals",
    "Carbon and its Compounds"
  ],
  "CBSE-10-Biology": [
    "Life Processes",
    "Control and Coordination",
    "How do Organisms Reproduce?",
    "Heredity",
    "Our Environment"
  ],
  "CBSE-10-Science": [
    "Chemical Reactions and Equations",
    "Acids, Bases and Salts",
    "Metals and Non-Metals",
    "Carbon and its Compounds",
    "Life Processes",
    "Control and Coordination",
    "How do Organisms Reproduce?",
    "Heredity",
    "Light – Reflection and Refraction",
    "The Human Eye and the Colourful World",
    "Electricity",
    "Magnetic Effects of Electric Current",
    "Our Environment"
  ],

  "CBSE-9-History": [
    "The French Revolution",
    "Socialism in Europe and the Russian Revolution",
    "Nazism and the Rise of Hitler",
    "Forest Society and Colonialism",
    "Pastoralists in the Modern World"
  ],
  "CBSE-9-Geography": [
    "India – Size and Location",
    "Physical Features of India",
    "Drainage",
    "Climate",
    "Natural Vegetation and Wildlife",
    "Population"
  ],
  "CBSE-9-Political Science": [
    "What is Democracy? Why Democracy?",
    "Constitutional Design",
    "Electoral Politics",
    "Working of Institutions",
    "Democratic Rights"
  ],
  "CBSE-9-Economics": [
    "The Story of Village Palampur",
    "People as Resource",
    "Poverty as a Challenge",
    "Food Security in India"
  ],
  "CBSE-10-History": [
    "The Rise of Nationalism in Europe",
    "Nationalism in India",
    "The Making of a Global World",
    "The Age of Industrialisation",
    "Print Culture and the Modern World"
  ],
  "CBSE-10-Geography": [
    "Resources and Development",
    "Forest and Wildlife Resources",
    "Water Resources",
    "Agriculture",
    "Minerals and Energy Resources",
    "Manufacturing Industries",
    "Lifelines of National Economy"
  ],
  "CBSE-10-Political Science": [
    "Power Sharing",
    "Federalism",
    "Gender, Religion and Caste",
    "Political Parties",
    "Outcomes of Democracy"
  ],
  "CBSE-10-Economics": [
    "Development",
    "Sectors of the Indian Economy",
    "Money and Credit",
    "Globalisation and the Indian Economy",
    "Consumer Rights"
  ],
"CBSE-10-Social Science": [
    "The Rise of Nationalism in Europe",
    "Nationalism in India",
    "The Making of a Global World",
    "The Age of Industrialisation",
    "Print Culture and the Modern World",
    "Resources and Development",
    "Forest and Wildlife Resources",
    "Water Resources",
    "Agriculture",
    "Minerals and Energy Resources",
    "Manufacturing Industries",
    "Lifelines of National Economy",
    "Power Sharing",
    "Federalism",
    "Gender, Religion and Caste",
    "Political Parties",
    "Outcomes of Democracy",
    "Development",
    "Sectors of the Indian Economy"
  ],
  "CBSE-11-Biology": [
    "The Living World",
    "Biological Classification",
    "Plant Kingdom",
    "Animal Kingdom",
    "Morphology of Flowering Plants",
    "Anatomy of Flowering Plants",
    "Structural Organisation in Animals",
    "Cell: The Unit of Life",
    "Biomolecules",
    "Cell Cycle and Cell Division",
    "Transport in Plants",
    "Mineral Nutrition",
    "Photosynthesis in Higher Plants",
    "Respiration in Plants",
    "Plant Growth and Development",
    "Digestion and Absorption",
    "Breathing and Exchange of Gases",
    "Body Fluids and Circulation",
    "Excretory Products and their Elimination",
    "Locomotion and Movement",
    "Neural Control and Coordination",
    "Chemical Coordination and Integration"
  ],
  "CBSE-11-Chemistry": [
    "Some Basic Concepts of Chemistry",
    "Structure of Atom",
    "Classification of Elements and Periodicity in Properties",
    "Chemical Bonding and Molecular Structure",
    "States of Matter",
    "Thermodynamics",
    "Equilibrium",
    "Redox Reactions",
    "Hydrogen",
    "The s-Block Elements",
    "The p-Block Elements",
    "Organic Chemistry – Some Basic Principles and Techniques",
    "Hydrocarbons",
    "Environmental Chemistry"
  ],
  "CBSE-11-Mathematics": [
    "Sets",
    "Relations and Functions",
    "Trigonometric Functions",
    "Principle of Mathematical Induction",
    "Complex Numbers and Quadratic Equations",
    "Linear Inequalities",
    "Permutations and Combinations",
    "Binomial Theorem",
    "Sequences and Series",
    "Straight Lines",
    "Conic Sections",
    "Introduction to Three Dimensional Geometry",
    "Limits and Derivatives",
    "Mathematical Reasoning",
    "Statistics",
    "Probability"
  ],
  "CBSE-11-Physics": [
    "Physical World",
    "Units and Measurements",
    "Motion in a Straight Line",
    "Motion in a Plane",
    "Laws of Motion",
    "Work, Energy and Power",
    "System of Particles and Rotational Motion",
    "Gravitation",
    "Mechanical Properties of Solids",
    "Mechanical Properties of Fluids",
    "Thermal Properties of Matter",
    "Thermodynamics",
    "Kinetic Theory",
    "Oscillations",
    "Waves"
  ],
  "CBSE-12-Biology": [
    "Reproduction in Organisms",
    "Sexual Reproduction in Flowering Plants",
    "Human Reproduction",
    "Reproductive Health",
    "Principles of Inheritance and Variation",
    "Molecular Basis of Inheritance",
    "Evolution",
    "Human Health and Disease",
    "Strategies for Enhancement in Food Production",
    "Microbes in Human Welfare",
    "Biotechnology: Principles and Processes",
    "Biotechnology and its Applications",
    "Organisms and Populations",
    "Ecosystem",
    "Biodiversity and Conservation",
    "Environmental Issues"
  ],
  "CBSE-12-Chemistry": [
    "The Solid State",
    "Solutions",
    "Electrochemistry",
    "Chemical Kinetics",
    "Surface Chemistry",
    "General Principles and Processes of Isolation of Elements",
    "The p-Block Elements",
    "The d- and f- Block Elements",
    "Coordination Compounds",
    "Haloalkanes and Haloarenes",
    "Alcohols, Phenols and Ethers",
    "Aldehydes, Ketones and Carboxylic Acids",
    "Amines",
    "Biomolecules",
    "Polymers",
    "Chemistry in Everyday Life"
  ],
  "CBSE-12-Mathematics": [
    "Relations and Functions",
    "Inverse Trigonometric Functions",
    "Matrices",
    "Determinants",
    "Continuity and Differentiability",
    "Application of Derivatives",
    "Integrals",
    "Application of Integrals",
    "Differential Equations",
    "Vector Algebra",
    "Three Dimensional Geometry",
    "Linear Programming",
    "Probability"
  ],
  "CBSE-12-Physics": [
    "Electric Charges and Fields",
    "Electrostatic Potential and Capacitance",
    "Current Electricity",
    "Moving Charges and Magnetism",
    "Magnetism and Matter",
    "Electromagnetic Induction",
    "Alternating Current",
    "Electromagnetic Waves",
    "Ray Optics and Optical Instruments",
    "Wave Optics",
    "Dual Nature of Radiation and Matter",
    "Atoms",
    "Nuclei",
    "Semiconductor Electronics",
    "Communication Systems"
  ],
  "CBSE-6-Mathematics": [
    "Knowing Our Numbers",
    "Whole Numbers",
    "Playing with Numbers",
    "Basic Geometrical Ideas",
    "Understanding Elementary Shapes",
    "Integers",
    "Fractions",
    "Decimals",
    "Data Handling",
    "Mensuration",
    "Algebra",
    "Ratio and Proportion",
    "Symmetry",
    "Practical Geometry"
  ],
  "CBSE-6-Science": [
    "Food: Where Does It Come From?",
    "Components of Food",
    "Fibre to Fabric",
    "Sorting Materials into Groups",
    "Separation of Substances",
    "Changes Around Us",
    "Getting to Know Plants",
    "Body Movements",
    "The Living Organisms and Their Surroundings",
    "Motion and Measurement of Distances",
    "Light, Shadows and Reflections",
    "Electricity and Circuits",
    "Fun with Magnets",
    "Water",
    "Air Around Us",
    "Garbage In, Garbage Out"
  ],
  "CBSE-6-History": [
    "What, Where, How and When?",
    "From Hunting–Gathering to Growing Food",
    "In the Earliest Cities",
    "What Books and Burials Tell Us",
    "Kingdoms, Kings and an Early Republic",
    "New Questions and Ideas",
    "Ashoka, The Emperor Who Gave Up War",
    "Vital Villages, Thriving Towns",
    "Traders, Kings and Pilgrims",
    "New Empires and Kingdoms",
    "Buildings, Paintings and Books"
  ],
  "CBSE-6-Geography": [
    "The Earth in the Solar System",
    "Globe: Latitudes and Longitudes",
    "Motions of the Earth",
    "Maps",
    "Major Domains of the Earth",
    "Major Landforms of the Earth",
    "Our Country – India",
    "India: Climate, Vegetation and Wildlife"
  ],
  "CBSE-6-Political Science": [
    "Understanding Diversity",
    "Diversity and Discrimination",
    "What is Government?",
    "Key Elements of a Democratic Government",
    "Panchayati Raj",
    "Rural Administration",
    "Urban Administration",
    "Rural Livelihoods",
    "Urban Livelihoods"
  ],
  "CBSE-6-Social Science": [
    "What, Where, How and When?",
    "From Hunting–Gathering to Growing Food",
    "In the Earliest Cities",
    "What Books and Burials Tell Us",
    "Kingdoms, Kings and an Early Republic",
    "New Questions and Ideas",
    "Ashoka, The Emperor Who Gave Up War",
    "Vital Villages, Thriving Towns",
    "Traders, Kings and Pilgrims",
    "New Empires and Kingdoms",
    "Buildings, Paintings and Books",
    "The Earth in the Solar System",
    "Globe: Latitudes and Longitudes",
    "Motions of the Earth",
    "Maps",
    "Major Domains of the Earth",
    "Major Landforms of the Earth",
    "Our Country – India",
    "India: Climate, Vegetation and Wildlife"
  ],
  "CBSE-7-Mathematics": [
    "Integers",
    "Fractions and Decimals",
    "Data Handling",
    "Simple Equations",
    "Lines and Angles",
    "The Triangle and its Properties",
    "Congruence of Triangles",
    "Comparing Quantities",
    "Rational Numbers",
    "Practical Geometry",
    "Perimeter and Area",
    "Algebraic Expressions",
    "Exponents and Powers",
    "Symmetry",
    "Visualising Solid Shapes"
  ],
  "CBSE-7-Science": [
    "Nutrition in Plants",
    "Nutrition in Animals",
    "Fibre to Fabric",
    "Heat",
    "Acids, Bases and Salts",
    "Physical and Chemical Changes",
    "Weather, Climate and Adaptations",
    "Winds, Storms and Cyclones",
    "Soil",
    "Respiration in Organisms",
    "Transportation in Animals and Plants",
    "Reproduction in Plants",
    "Motion and Time",
    "Electric Current and its Effects",
    "Light",
    "Water: A Precious Resource",
    "Forests: Our Lifeline",
    "Wastewater Story"
  ],
  "CBSE-7-History": [
    "Tracing Changes Through a Thousand Years",
    "New Kings and Kingdoms",
    "The Delhi Sultans",
    "The Mughal Empire",
    "Rulers and Buildings",
    "Towns, Traders and Craftspersons",
    "Tribes, Nomads and Settled Communities",
    "Devotional Paths to the Divine",
    "The Making of Regional Cultures",
    "Eighteenth-Century Political Formations"
  ],
  "CBSE-7-Geography": [
    "Environment",
    "Inside Our Earth",
    "Our Changing Earth",
    "Air",
    "Water",
    "Natural Vegetation and Wildlife"
  ],
  "CBSE-7-Political Science": [
    "Equality",
    "Role of the Government in Health",
    "How the State Government Works",
    "Growing up as Boys and Girls",
    "Women Change the World",
    "Understanding Media",
    "Markets Around Us",
    "A Shirt in the Market"
  ],
  "CBSE-7-Social Science": [
    "Tracing Changes Through a Thousand Years",
    "New Kings and Kingdoms",
    "The Delhi Sultans",
    "The Mughal Empire",
    "Rulers and Buildings",
    "Towns, Traders and Craftspersons",
    "Tribes, Nomads and Settled Communities",
    "Devotional Paths to the Divine",
    "The Making of Regional Cultures",
    "Eighteenth-Century Political Formations",
    "Environment",
    "Inside Our Earth",
    "Our Changing Earth",
    "Air",
    "Water",
    "Natural Vegetation and Wildlife"
  ],
  "CBSE-8-Mathematics": [
    "Rational Numbers",
    "Linear Equations in One Variable",
    "Understanding Quadrilaterals",
    "Practical Geometry",
    "Data Handling",
    "Squares and Square Roots",
    "Cubes and Cube Roots",
    "Comparing Quantities",
    "Algebraic Expressions and Identities",
    "Visualising Solid Shapes",
    "Mensuration",
    "Exponents and Powers",
    "Direct and Inverse Proportions",
    "Factorisation",
    "Introduction to Graphs",
    "Playing with Numbers"
  ],
  "CBSE-8-Science": [
    "Crop Production and Management",
    "Microorganisms: Friend and Foe",
    "Synthetic Fibres and Plastics",
    "Materials: Metals and Non-Metals",
    "Coal and Petroleum",
    "Combustion and Flame",
    "Conservation of Plants and Animals",
    "Cell - Structure and Functions",
    "Reproduction in Animals",
    "Reaching the Age of Adolescence",
    "Force and Pressure",
    "Friction",
    "Sound",
    "Chemical Effects of Electric Current",
    "Some Natural Phenomena",
    "Light",
    "Stars and The Solar System",
    "Pollution of Air and Water"
  ],
  "CBSE-8-History": [
    "How, When and Where",
    "From Trade to Territory",
    "Ruling the Countryside",
    "Tribals, Dikus and the Vision of a Golden Age",
    "When People Rebel",
    "Weavers, Iron Smelters and Factory Owners",
    "Civilising the 'Native', Educating the Nation",
    "Women, Caste and Reform",
    "The Making of the National Movement",
    "India After Independence"
  ],
  "CBSE-8-Geography": [
    "Resources",
    "Land, Soil, Water, Natural Vegetation and Wildlife",
    "Mineral and Power Resources",
    "Agriculture",
    "Industries",
    "Human Resources"
  ],
  "CBSE-8-Political Science": [
    "The Indian Constitution",
    "Understanding Secularism"
  ],
  "CBSE-8-Social Science": [
    "How, When and Where",
    "From Trade to Territory",
    "Ruling the Countryside",
    "Tribals, Dikus and the Vision of a Golden Age",
    "When People Rebel",
    "Weavers, Iron Smelters and Factory Owners",
    "Civilising the 'Native', Educating the Nation",
    "Women, Caste and Reform",
    "The Making of the National Movement",
    "India After Independence",
    "Resources",
    "Land, Soil, Water, Natural Vegetation and Wildlife",
    "Mineral and Power Resources",
    "Agriculture",
    "Industries",
    "Human Resources",
    "The Indian Constitution",
    "Understanding Secularism"
  ],
  "CBSE-9-Mathematics": [
    "Number Systems",
    "Polynomials",
    "Coordinate Geometry",
    "Linear Equations in Two Variables",
    "Introduction to Euclid’s Geometry",
    "Lines and Angles",
    "Triangles",
    "Quadrilaterals",
    "Circles",
    "Heron’s Formula",
    "Surface Areas and Volumes",
    "Statistics"
  ],
  "CBSE-9-Physics": [
    "Motion",
    "Force and Laws of Motion",
    "Gravitation",
    "Work and Energy",
    "Sound"
  ],
  "CBSE-9-Chemistry": [
    "Matter in Our Surroundings",
    "Is Matter Around Us Pure",
    "Atoms and Molecules",
    "Structure of the Atom"
  ],
  "CBSE-9-Biology": [
    "The Fundamental Unit of Life",
    "Tissues",
    "Improvement in Food Resources"
  ],
  "CBSE-9-Science": [
    "Matter in Our Surroundings",
    "Is Matter Around Us Pure",
    "Atoms and Molecules",
    "Structure of the Atom",
    "The Fundamental Unit of Life",
    "Tissues",
    "Motion",
    "Force and Laws of Motion",
    "Gravitation",
    "Work and Energy",
    "Sound",
    "Improvement in Food Resources"
  ],
  "CBSE-9-Social Science": [
    "The French Revolution",
    "Socialism in Europe and the Russian Revolution",
    "Nazism and the Rise of Hitler",
    "Forest Society and Colonialism",
    "Pastoralists in the Modern World",
    "India – Size and Location",
    "Physical Features of India",
    "Drainage",
    "Climate",
    "Natural Vegetation and Wildlife",
    "Population",
    "What is Democracy? Why Democracy?",
    "Constitutional Design",
    "Electoral Politics",
    "Working of Institutions",
    "Democratic Rights"
  ],
  "CBSE-COMPETITION-Biology": [
    "जीवधारियों का वर्गीकरण",
    "कोशिका विज्ञान",
    "जैव-विकास",
    "आनुवंशिकी",
    "वनस्पति विज्ञान",
    "पारिस्थितिकी",
    "प्रदूषण",
    "प्राणी विज्ञान",
    "मानव शरीर के तंत्र",
    "पोषक पदार्थ",
    "पोषण",
    "मानव रोग",
    "विविध",
    "विज्ञान की कुछ प्रमुख शाखाएँ"
  ],
  "CBSE-COMPETITION-Chemistry": [
    "पदार्थ एवं उसकी प्रकृति",
    "परमाणु संरचना",
    "गैसों का आचरण",
    "तत्वों का आवर्ती वर्गीकरण",
    "रासायनिक बंधन",
    "ऑक्सीकरण एवं अवकरण",
    "अम्ल, भस्म एवं लवण",
    "विलयन",
    "कार्बन एवं उसके यौगिक",
    "ईंधन",
    "धातुएँ",
    "अधातुएँ",
    "मिश्रधातु",
    "मानव निर्मित पदार्थ",
    "उत्प्रेरण"
  ],
  "CBSE-COMPETITION-Economics": [
    "अर्थशास्त्र और अर्थव्यवस्था",
    "अर्थव्यवस्था के क्षेत्र",
    "आर्थिक संवृद्धि एवं आर्थिक विकास",
    "मानव विकास रिपोर्ट 2025",
    "खुशहाली",
    "विश्व खुशहाली रिपोर्ट-2025",
    "विश्व खुशहाली रिपोर्ट-2025",
    "वैश्विक लैंगिक अंतराल रिपोर्ट-2025",
    "राष्ट्रीय आय",
    "आर्थिक आयोजन",
    "गरीबी",
    "भारत में निर्धनता",
    "नई आर्थिक नीति",
    "भारतीय वित्त व्यवस्था",
    "भारत में पत्र मुद्रा",
    "भारत में प्रतिभूति-मुद्रण एवं सिक्कों का उत्पादन",
    "टकसाल (Mints)",
    "भारतीय प्रतिभूति एवं विनिमय बोर्ड (SEBI)",
    "भारत के प्रमुख शेयर बाजार",
    "भारत के प्रमुख शेयर मूल्य सूचकांक",
    "बजट (Budget)",
    "कर (Tax)",
    "वस्तु एवं सेवाकर (Goods & Service Tax)",
    "कृषि",
    "उद्योग",
    "विदेशी व्यापार एवं भुगतान संतुलन",
    "अर्थशास्त्र : परीक्षोपयोगी तथ्य",
    "महत्वपूर्ण आर्थिक शब्दावली"
  ],
  "CBSE-COMPETITION-Geography": [
    "भारत का भूगोल सामान्य जानकारी",
    "भारत का भौतिक स्वरूप",
    "भारत की नदियाँ",
    "भारत की प्रमुख झीलें",
    "भारत के प्रमुख जलप्रपात",
    "भारत की जलवायु",
    "भारत की मिट्टी",
    "भारत की कृषि",
    "भारत में सिंचाई",
    "भारत के खनिज संसाधन",
    "भारत के उद्योग",
    "भारत में परिवहन",
    "भारत की जनगणना 2011",
    "भारत की प्रमुख बहुउद्देशीय नदी घाटी परियोजनाएँ",
    "नदियों के किनारे बसे प्रमुख नगर",
    "भारत के पर्वतीय नगर",
    "भारत के प्रमुख वन्य जीव अभयारण्य/राष्ट्रीय उद्यान",
    "भारत के बाघ अभयारण्य",
    "भारत के प्रमुख भौगोलिक उपनाम",
    "भारतीय राज्यों एवं केन्द्रशासित प्रदेशों की राजधानी",
    "भारतीय जनजातियाँ"
  ],
  "CBSE-COMPETITION-History": [
    "प्राचीन भारतीय इतिहास के स्रोत",
    "प्रागैतिहासिक काल",
    "सिंधु सभ्यता",
    "वैदिक सभ्यता",
    "महाजनपदों का उदय",
    "जैन धर्म",
    "बौद्ध धर्म",
    "शैव धर्म",
    "वैष्णव धर्म",
    "इस्लाम धर्म",
    "ईसाई धर्म",
    "पारसी धर्म",
    "मगध राज्य का उत्कर्ष",
    "सिकंदर",
    "मौर्य साम्राज्य",
    "ब्राह्मण साम्राज्य",
    "भारत के यवन राज्य",
    "शक",
    "कुषाण",
    "संगम युग",
    "गुप्त साम्राज्य",
    "वाकाटक राजवंश",
    "पुष्यभूति वंश या वर्द्धन वंश",
    "दक्षिण भारत के प्रमुख राजवंश",
    "सीमावर्ती राजवंशों का अभ्युदय",
    "राजपूत राजवंशों की उत्पत्ति",
    "भारत पर अरबों का आक्रमण",
    "महमूद गजनवी",
    "मुहम्मद गौरी",
    "सल्तनत काल",
    "विजयनगर साम्राज्य",
    "बहमनी राज्य",
    "स्वतंत्र प्रान्तीय राज्य",
    "सूफी आन्दोलन",
    "भक्ति आन्दोलन",
    "मुगल साम्राज्य",
    "मुगल शासन व्यवस्था",
    "मराठों का उत्कर्ष",
    "उत्तरकालीन मुगल सम्राट",
    "भारत में यूरोपीय व्यापारिक कंपनियों का आगमन",
    "बंगाल पर अंग्रेजों का आधिपत्य",
    "अंग्रेजों के मैसूर से संबंध",
    "सिक्ख एवं अंग्रेज",
    "कंपनी के अधीन गवर्नर जेनरल",
    "अंग्रेजी शासन के विरुद्ध महत्वपूर्ण विद्रोह",
    "1857 ई. की महान क्रांति",
    "1857 ई. की महान क्रांति के प्रमुख केंद्र",
    "भारत का स्वतंत्रता संघर्ष: महत्वपूर्ण तथ्य",
    "भारतीय धार्मिक, सामाजिक एवं राष्ट्रीय आन्दोलन से संबंधित महत्वपूर्ण संगठन एवं संस्थाएँ",
    "भारतीय राष्ट्रीय आन्दोलन में संबंधित आन्दोलन एवं घटनाएँ",
    "भारत के महान शहीद",
    "भारतीय स्वतंत्रता आन्दोलन के प्रमुख वचन एवं नारे",
    "स्वतंत्रता आंदोलन से संबंधित प्रकाशित पत्र, पत्रिकाएँ एवं पुस्तकें",
    "उपाधि, प्राप्तकर्ता एवं दाता",
    "कांग्रेस अधिवेशन: कब और कहाँ",
    "ब्रिटिशकालीन आयोग/समितियाँ",
    "भारतीय प्रेस का विकास",
    "भारत की ऐतिहासिक लड़ाइयाँ",
    "प्रमुख राजवंश, संस्थापक तथा राजधानी",
    "सामाजिक सुधार अधिनियम",
    "मुस्लिम सामाजिक धार्मिक आन्दोलन और संगठन"
  ],
  "CBSE-COMPETITION-Physics": [
    "मात्रक",
    "गति",
    "कार्य, ऊर्जा एवं शक्ति",
    "गुरुत्वाकर्षण",
    "दाब",
    "प्लवन",
    "पृष्ठ तनाव",
    "श्यानता",
    "प्रत्यास्थता",
    "सरल आवर्त गति",
    "तरंग",
    "ध्वनि तरंग",
    "ऊष्मा",
    "प्रकाश",
    "स्थिर वैद्युत",
    "विद्युत् धारा",
    "चुम्बकत्व",
    "परमाणु भौतिकी",
    "रेडियोसक्रियता",
    "नाभिकीय विखंडन तथा संलयन",
    "ब्रह्मांड"
  ],
  "CBSE-COMPETITION-Political Science": [
    "भारतीय संविधान के विकास का संक्षिप्त इतिहास",
    "भारतीय संविधान सभा",
    "भारतीय संविधान की उद्देशिका अथवा प्रस्तावना",
    "भारतीय संविधान के विदेशी स्रोत",
    "भारतीय संविधान की अनुसूची",
    "देशी रियासतों का भारत में विलय",
    "संघ और राज्य क्षेत्र",
    "राज्यों का पुनर्गठन",
    "भारतीय नागरिकता",
    "मौलिक अधिकार",
    "राज्य के नीति निर्देशक सिद्धांत (DPSP)",
    "मौलिक कर्तव्य",
    "संघीय कार्यपालिका",
    "संघीय संसद",
    "भारत का महान्यायवादी (Attorney General of India)",
    "भारत का नियंत्रक एवं महालेखा परीक्षक (CAG)",
    "भारत की संचित निधि",
    "भारत की आकस्मिकता निधि",
    "संविधान में संशोधन",
    "न्यायपालिका",
    "राज्य की कार्यपालिका",
    "केन्द्र-राज्य संबंध",
    "अंतर्राज्य परिषद्",
    "नीति आयोग",
    "राष्ट्रीय विकास परिषद्",
    "वित्त आयोग",
    "लोक सेवा आयोग",
    "निर्वाचन आयोग",
    "परिसीमन आयोग",
    "भारतीय राजव्यवस्था में वरीयता अनुक्रम (Order of Precedence)",
    "राजभाषा",
    "आपात उपबन्ध",
    "जम्मू-कश्मीर को विशेष संवैधानिक दर्जा",
    "भारत के राष्ट्रीय चिह्न",
    "संसद की वित्तीय समितियाँ",
    "पंचायती राज",
    "महत्वपूर्ण शब्दावलियाँ",
    "संविधान के कुछ महत्वपूर्ण अनुच्छेद",
    "संविधान में किये गए प्रमुख संशोधन"
  ],
  "COMPETITION-COMPETITION-Biology": [
    "जीवधारियों का वर्गीकरण",
    "कोशिका विज्ञान",
    "जैव-विकास",
    "आनुवंशिकी",
    "वनस्पति विज्ञान",
    "पारिस्थितिकी",
    "प्रदूषण",
    "प्राणी विज्ञान",
    "मानव शरीर के तंत्र",
    "पोषक पदार्थ",
    "पोषण",
    "मानव रोग",
    "विविध",
    "विज्ञान की कुछ प्रमुख शाखाएँ"
  ],
  "COMPETITION-COMPETITION-Chemistry": [
    "पदार्थ एवं उसकी प्रकृति",
    "परमाणु संरचना",
    "गैसों का आचरण",
    "तत्वों का आवर्ती वर्गीकरण",
    "रासायनिक बंधन",
    "ऑक्सीकरण एवं अवकरण",
    "अम्ल, भस्म एवं लवण",
    "विलयन",
    "कार्बन एवं उसके यौगिक",
    "ईंधन",
    "धातुएँ",
    "अधातुएँ",
    "मिश्रधातु",
    "मानव निर्मित पदार्थ",
    "उत्प्रेरण"
  ],
  "COMPETITION-COMPETITION-Economics": [
    "अर्थशास्त्र और अर्थव्यवस्था",
    "अर्थव्यवस्था के क्षेत्र",
    "आर्थिक संवृद्धि एवं आर्थिक विकास",
    "मानव विकास रिपोर्ट 2025",
    "खुशहाली",
    "विश्व खुशहाली रिपोर्ट-2025",
    "विश्व खुशहाली रिपोर्ट-2025",
    "वैश्विक लैंगिक अंतराल रिपोर्ट-2025",
    "राष्ट्रीय आय",
    "आर्थिक आयोजन",
    "गरीबी",
    "भारत में निर्धनता",
    "नई आर्थिक नीति",
    "भारतीय वित्त व्यवस्था",
    "भारत में पत्र मुद्रा",
    "भारत में प्रतिभूति-मुद्रण एवं सिक्कों का उत्पादन",
    "टकसाल (Mints)",
    "भारतीय प्रतिभूति एवं विनिमय बोर्ड (SEBI)",
    "भारत के प्रमुख शेयर बाजार",
    "भारत के प्रमुख शेयर मूल्य सूचकांक",
    "बजट (Budget)",
    "कर (Tax)",
    "वस्तु एवं सेवाकर (Goods & Service Tax)",
    "कृषि",
    "उद्योग",
    "विदेशी व्यापार एवं भुगतान संतुलन",
    "अर्थशास्त्र : परीक्षोपयोगी तथ्य",
    "महत्वपूर्ण आर्थिक शब्दावली"
  ],
  "COMPETITION-COMPETITION-Geography": [
    "भारत का भूगोल सामान्य जानकारी",
    "भारत का भौतिक स्वरूप",
    "भारत की नदियाँ",
    "भारत की प्रमुख झीलें",
    "भारत के प्रमुख जलप्रपात",
    "भारत की जलवायु",
    "भारत की मिट्टी",
    "भारत की कृषि",
    "भारत में सिंचाई",
    "भारत के खनिज संसाधन",
    "भारत के उद्योग",
    "भारत में परिवहन",
    "भारत की जनगणना 2011",
    "भारत की प्रमुख बहुउद्देशीय नदी घाटी परियोजनाएँ",
    "नदियों के किनारे बसे प्रमुख नगर",
    "भारत के पर्वतीय नगर",
    "भारत के प्रमुख वन्य जीव अभयारण्य/राष्ट्रीय उद्यान",
    "भारत के बाघ अभयारण्य",
    "भारत के प्रमुख भौगोलिक उपनाम",
    "भारतीय राज्यों एवं केन्द्रशासित प्रदेशों की राजधानी",
    "भारतीय जनजातियाँ"
  ],
  "COMPETITION-COMPETITION-History": [
    "प्राचीन भारतीय इतिहास के स्रोत",
    "प्रागैतिहासिक काल",
    "सिंधु सभ्यता",
    "वैदिक सभ्यता",
    "महाजनपदों का उदय",
    "जैन धर्म",
    "बौद्ध धर्म",
    "शैव धर्म",
    "वैष्णव धर्म",
    "इस्लाम धर्म",
    "ईसाई धर्म",
    "पारसी धर्म",
    "मगध राज्य का उत्कर्ष",
    "सिकंदर",
    "मौर्य साम्राज्य",
    "ब्राह्मण साम्राज्य",
    "भारत के यवन राज्य",
    "शक",
    "कुषाण",
    "संगम युग",
    "गुप्त साम्राज्य",
    "वाकाटक राजवंश",
    "पुष्यभूति वंश या वर्द्धन वंश",
    "दक्षिण भारत के प्रमुख राजवंश",
    "सीमावर्ती राजवंशों का अभ्युदय",
    "राजपूत राजवंशों की उत्पत्ति",
    "भारत पर अरबों का आक्रमण",
    "महमूद गजनवी",
    "मुहम्मद गौरी",
    "सल्तनत काल",
    "विजयनगर साम्राज्य",
    "बहमनी राज्य",
    "स्वतंत्र प्रान्तीय राज्य",
    "सूफी आन्दोलन",
    "भक्ति आन्दोलन",
    "मुगल साम्राज्य",
    "मुगल शासन व्यवस्था",
    "मराठों का उत्कर्ष",
    "उत्तरकालीन मुगल सम्राट",
    "भारत में यूरोपीय व्यापारिक कंपनियों का आगमन",
    "बंगाल पर अंग्रेजों का आधिपत्य",
    "अंग्रेजों के मैसूर से संबंध",
    "सिक्ख एवं अंग्रेज",
    "कंपनी के अधीन गवर्नर जेनरल",
    "अंग्रेजी शासन के विरुद्ध महत्वपूर्ण विद्रोह",
    "1857 ई. की महान क्रांति",
    "1857 ई. की महान क्रांति के प्रमुख केंद्र",
    "भारत का स्वतंत्रता संघर्ष: महत्वपूर्ण तथ्य",
    "भारतीय धार्मिक, सामाजिक एवं राष्ट्रीय आन्दोलन से संबंधित महत्वपूर्ण संगठन एवं संस्थाएँ",
    "भारतीय राष्ट्रीय आन्दोलन में संबंधित आन्दोलन एवं घटनाएँ",
    "भारत के महान शहीद",
    "भारतीय स्वतंत्रता आन्दोलन के प्रमुख वचन एवं नारे",
    "स्वतंत्रता आंदोलन से संबंधित प्रकाशित पत्र, पत्रिकाएँ एवं पुस्तकें",
    "उपाधि, प्राप्तकर्ता एवं दाता",
    "कांग्रेस अधिवेशन: कब और कहाँ",
    "ब्रिटिशकालीन आयोग/समितियाँ",
    "भारतीय प्रेस का विकास",
    "भारत की ऐतिहासिक लड़ाइयाँ",
    "प्रमुख राजवंश, संस्थापक तथा राजधानी",
    "सामाजिक सुधार अधिनियम",
    "मुस्लिम सामाजिक धार्मिक आन्दोलन और संगठन"
  ],
  "COMPETITION-COMPETITION-Physics": [
    "मात्रक",
    "गति",
    "कार्य, ऊर्जा एवं शक्ति",
    "गुरुत्वाकर्षण",
    "दाब",
    "प्लवन",
    "पृष्ठ तनाव",
    "श्यानता",
    "प्रत्यास्थता",
    "सरल आवर्त गति",
    "तरंग",
    "ध्वनि तरंग",
    "ऊष्मा",
    "प्रकाश",
    "स्थिर वैद्युत",
    "विद्युत् धारा",
    "चुम्बकत्व",
    "परमाणु भौतिकी",
    "रेडियोसक्रियता",
    "नाभिकीय विखंडन तथा संलयन",
    "ब्रह्मांड"
  ],
  "COMPETITION-COMPETITION-Political Science": [
    "भारतीय संविधान के विकास का संक्षिप्त इतिहास",
    "भारतीय संविधान सभा",
    "भारतीय संविधान की उद्देशिका अथवा प्रस्तावना",
    "भारतीय संविधान के विदेशी स्रोत",
    "भारतीय संविधान की अनुसूची",
    "देशी रियासतों का भारत में विलय",
    "संघ और राज्य क्षेत्र",
    "राज्यों का पुनर्गठन",
    "भारतीय नागरिकता",
    "मौलिक अधिकार",
    "राज्य के नीति निर्देशक सिद्धांत (DPSP)",
    "मौलिक कर्तव्य",
    "संघीय कार्यपालिका",
    "संघीय संसद",
    "भारत का महान्यायवादी (Attorney General of India)",
    "भारत का नियंत्रक एवं महालेखा परीक्षक (CAG)",
    "भारत की संचित निधि",
    "भारत की आकस्मिकता निधि",
    "संविधान में संशोधन",
    "न्यायपालिका",
    "राज्य की कार्यपालिका",
    "केन्द्र-राज्य संबंध",
    "अंतर्राज्य परिषद्",
    "नीति आयोग",
    "राष्ट्रीय विकास परिषद्",
    "वित्त आयोग",
    "लोक सेवा आयोग",
    "निर्वाचन आयोग",
    "परिसीमन आयोग",
    "भारतीय राजव्यवस्था में वरीयता अनुक्रम (Order of Precedence)",
    "राजभाषा",
    "आपात उपबन्ध",
    "जम्मू-कश्मीर को विशेष संवैधानिक दर्जा",
    "भारत के राष्ट्रीय चिह्न",
    "संसद की वित्तीय समितियाँ",
    "पंचायती राज",
    "महत्वपूर्ण शब्दावलियाँ",
    "संविधान के कुछ महत्वपूर्ण अनुच्छेद",
    "संविधान में किये गए प्रमुख संशोधन"
  ]
};