// Shared list of branded fonts available for the splash / loading screen
// app-short-name. Used by both AppLoadingScreen (renderer) and AdminDashboard
// (admin picker). When the admin picks one, it'''s saved to
// SystemSettings.splashFontId and applied globally for every user.

export type SplashFont = {
  id: string;
  label: string;
  family: string;
  gfontParam: string;
  letterSpacing?: string;
};

export const SPLASH_FONTS: SplashFont[] = [
  { id: 'default', label: 'Default', family: '', gfontParam: '' },
  { id: 'orbitron', label: 'Orbitron · Tech', family: '"Orbitron", sans-serif', gfontParam: 'Orbitron:wght@900', letterSpacing: '0.05em' },
  { id: 'audiowide', label: 'Audiowide', family: '"Audiowide", sans-serif', gfontParam: 'Audiowide' },
  { id: 'russo', label: 'Russo One · Bold', family: '"Russo One", sans-serif', gfontParam: 'Russo+One' },
  { id: 'bebas', label: 'Bebas Neue', family: '"Bebas Neue", sans-serif', gfontParam: 'Bebas+Neue', letterSpacing: '0.08em' },
  { id: 'blackops', label: 'Black Ops · Military', family: '"Black Ops One", sans-serif', gfontParam: 'Black+Ops+One' },
  { id: 'righteous', label: 'Righteous', family: '"Righteous", sans-serif', gfontParam: 'Righteous' },
  { id: 'monoton', label: 'Monoton · Neon', family: '"Monoton", sans-serif', gfontParam: 'Monoton' },
  { id: 'playfair', label: 'Playfair · Elegant', family: '"Playfair Display", serif', gfontParam: 'Playfair+Display:wght@900' },
  { id: 'cinzel', label: 'Cinzel · Classic', family: '"Cinzel", serif', gfontParam: 'Cinzel:wght@900', letterSpacing: '0.06em' },
  { id: 'marker', label: 'Permanent Marker', family: '"Permanent Marker", cursive', gfontParam: 'Permanent+Marker' },
  { id: 'pressstart', label: 'Press Start · Retro', family: '"Press Start 2P", monospace', gfontParam: 'Press+Start+2P' },
  { id: 'pacifico', label: 'Pacifico · Casual', family: '"Pacifico", cursive', gfontParam: 'Pacifico' },
  { id: 'rajdhani', label: 'Rajdhani · Modern', family: '"Rajdhani", sans-serif', gfontParam: 'Rajdhani:wght@700' },
  { id: 'abril_fatface', label: 'Abril Fatface', family: '"Abril Fatface", display', gfontParam: 'Abril+Fatface' },
  { id: 'alfa_slab_one', label: 'Alfa Slab One', family: '"Alfa Slab One", display', gfontParam: 'Alfa+Slab+One' },
  { id: 'anton', label: 'Anton', family: '"Anton", display', gfontParam: 'Anton' },
  { id: 'archivo_black', label: 'Archivo Black', family: '"Archivo Black", display', gfontParam: 'Archivo+Black:wght@900' },
  { id: 'bangers', label: 'Bangers', family: '"Bangers", display', gfontParam: 'Bangers' },
  { id: 'black_han_sans', label: 'Black Han Sans', family: '"Black Han Sans", display', gfontParam: 'Black+Han+Sans' },
  { id: 'bowlby_one', label: 'Bowlby One', family: '"Bowlby One", display', gfontParam: 'Bowlby+One' },
  { id: 'bungee', label: 'Bungee', family: '"Bungee", display', gfontParam: 'Bungee' },
  { id: 'bungee_shade', label: 'Bungee Shade', family: '"Bungee Shade", display', gfontParam: 'Bungee+Shade' },
  { id: 'bungee_inline', label: 'Bungee Inline', family: '"Bungee Inline", display', gfontParam: 'Bungee+Inline' },
  { id: 'bungee_outline', label: 'Bungee Outline', family: '"Bungee Outline", display', gfontParam: 'Bungee+Outline' },
  { id: 'cabin_sketch', label: 'Cabin Sketch', family: '"Cabin Sketch", display', gfontParam: 'Cabin+Sketch' },
  { id: 'carter_one', label: 'Carter One', family: '"Carter One", display', gfontParam: 'Carter+One' },
  { id: 'caveat', label: 'Caveat', family: '"Caveat", display', gfontParam: 'Caveat' },
  { id: 'changa_one', label: 'Changa One', family: '"Changa One", display', gfontParam: 'Changa+One' },
  { id: 'chela_one', label: 'Chela One', family: '"Chela One", display', gfontParam: 'Chela+One' },
  { id: 'chewy', label: 'Chewy', family: '"Chewy", display', gfontParam: 'Chewy' },
  { id: 'chonburi', label: 'Chonburi', family: '"Chonburi", display', gfontParam: 'Chonburi' },
  { id: 'concert_one', label: 'Concert One', family: '"Concert One", display', gfontParam: 'Concert+One' },
  { id: 'crete_round', label: 'Crete Round', family: '"Crete Round", display', gfontParam: 'Crete+Round' },
  { id: 'damion', label: 'Damion', family: '"Damion", display', gfontParam: 'Damion' },
  { id: 'dancing_script', label: 'Dancing Script', family: '"Dancing Script", display', gfontParam: 'Dancing+Script' },
  { id: 'days_one', label: 'Days One', family: '"Days One", display', gfontParam: 'Days+One' },
  { id: 'dela_gothic_one', label: 'Dela Gothic One', family: '"Dela Gothic One", display', gfontParam: 'Dela+Gothic+One' },
  { id: 'diplomata', label: 'Diplomata', family: '"Diplomata", display', gfontParam: 'Diplomata' },
  { id: 'diplomata_sc', label: 'Diplomata SC', family: '"Diplomata SC", display', gfontParam: 'Diplomata+SC' },
  { id: 'dm_serif_display', label: 'DM Serif Display', family: '"DM Serif Display", display', gfontParam: 'DM+Serif+Display' },
  { id: 'doppio_one', label: 'Doppio One', family: '"Doppio One", display', gfontParam: 'Doppio+One' },
  { id: 'eater', label: 'Eater', family: '"Eater", display', gfontParam: 'Eater' },
  { id: 'faster_one', label: 'Faster One', family: '"Faster One", display', gfontParam: 'Faster+One' },
  { id: 'fira_sans_black', label: 'Fira Sans Black', family: '"Fira Sans Black", display', gfontParam: 'Fira+Sans+Black:wght@900' },
  { id: 'fjalla_one', label: 'Fjalla One', family: '"Fjalla One", display', gfontParam: 'Fjalla+One' },
  { id: 'fontdiner_swanky', label: 'Fontdiner Swanky', family: '"Fontdiner Swanky", display', gfontParam: 'Fontdiner+Swanky' },
  { id: 'fredericka_the_great', label: 'Fredericka the Great', family: '"Fredericka the Great", display', gfontParam: 'Fredericka+the+Great' },
  { id: 'fredoka_one', label: 'Fredoka One', family: '"Fredoka One", display', gfontParam: 'Fredoka+One' },
  { id: 'frijole', label: 'Frijole', family: '"Frijole", display', gfontParam: 'Frijole' },
  { id: 'fugaz_one', label: 'Fugaz One', family: '"Fugaz One", display', gfontParam: 'Fugaz+One' },
  { id: 'galindo', label: 'Galindo', family: '"Galindo", display', gfontParam: 'Galindo' },
  { id: 'genos', label: 'Genos', family: '"Genos", display', gfontParam: 'Genos' },
  { id: 'glegoo', label: 'Glegoo', family: '"Glegoo", display', gfontParam: 'Glegoo' },
  { id: 'gloock', label: 'Gloock', family: '"Gloock", display', gfontParam: 'Gloock' },
  { id: 'goblin_one', label: 'Goblin One', family: '"Goblin One", display', gfontParam: 'Goblin+One' },
  { id: 'graduate', label: 'Graduate', family: '"Graduate", display', gfontParam: 'Graduate' },
  { id: 'great_vibes', label: 'Great Vibes', family: '"Great Vibes", display', gfontParam: 'Great+Vibes' },
  { id: 'hammersmith_one', label: 'Hammersmith One', family: '"Hammersmith One", display', gfontParam: 'Hammersmith+One' },
  { id: 'hanalei_fill', label: 'Hanalei Fill', family: '"Hanalei Fill", display', gfontParam: 'Hanalei+Fill' },
  { id: 'holtwood_one_sc', label: 'Holtwood One SC', family: '"Holtwood One SC", display', gfontParam: 'Holtwood+One+SC' },
  { id: 'iceland', label: 'Iceland', family: '"Iceland", display', gfontParam: 'Iceland' },
  { id: 'indie_flower', label: 'Indie Flower', family: '"Indie Flower", display', gfontParam: 'Indie+Flower' },
  { id: 'jaro', label: 'Jaro', family: '"Jaro", display', gfontParam: 'Jaro' },
  { id: 'jersey_10', label: 'Jersey 10', family: '"Jersey 10", display', gfontParam: 'Jersey+10' },
  { id: 'jersey_15', label: 'Jersey 15', family: '"Jersey 15", display', gfontParam: 'Jersey+15' },
  { id: 'jersey_20', label: 'Jersey 20', family: '"Jersey 20", display', gfontParam: 'Jersey+20' },
  { id: 'jersey_25', label: 'Jersey 25', family: '"Jersey 25", display', gfontParam: 'Jersey+25' },
  { id: 'josefin_sans', label: 'Josefin Sans', family: '"Josefin Sans", display', gfontParam: 'Josefin+Sans' },
  { id: 'jost', label: 'Jost', family: '"Jost", display', gfontParam: 'Jost' },
  { id: 'jua', label: 'Jua', family: '"Jua", display', gfontParam: 'Jua' },
  { id: 'just_another_hand', label: 'Just Another Hand', family: '"Just Another Hand", display', gfontParam: 'Just+Another+Hand' },
  { id: 'kalam', label: 'Kalam', family: '"Kalam", display', gfontParam: 'Kalam' },
  { id: 'kanit', label: 'Kanit', family: '"Kanit", display', gfontParam: 'Kanit' },
  { id: 'kaushan_script', label: 'Kaushan Script', family: '"Kaushan Script", display', gfontParam: 'Kaushan+Script' },
  { id: 'keania_one', label: 'Keania One', family: '"Keania One", display', gfontParam: 'Keania+One' },
  { id: 'khand', label: 'Khand', family: '"Khand", display', gfontParam: 'Khand' },
  { id: 'knewave', label: 'Knewave', family: '"Knewave", display', gfontParam: 'Knewave' },
  { id: 'koulen', label: 'Koulen', family: '"Koulen", display', gfontParam: 'Koulen' },
  { id: 'kranky', label: 'Kranky', family: '"Kranky", display', gfontParam: 'Kranky' },
  { id: 'krona_one', label: 'Krona One', family: '"Krona One", display', gfontParam: 'Krona+One' },
  { id: 'lalezar', label: 'Lalezar', family: '"Lalezar", display', gfontParam: 'Lalezar' },
  { id: 'lemon', label: 'Lemon', family: '"Lemon", display', gfontParam: 'Lemon' },
  { id: 'lemonada', label: 'Lemonada', family: '"Lemonada", display', gfontParam: 'Lemonada' },
  { id: 'lobster', label: 'Lobster', family: '"Lobster", display', gfontParam: 'Lobster' },
  { id: 'lobster_two', label: 'Lobster Two', family: '"Lobster Two", display', gfontParam: 'Lobster+Two' },
  { id: 'londrina_solid', label: 'Londrina Solid', family: '"Londrina Solid", display', gfontParam: 'Londrina+Solid' },
  { id: 'luckiest_guy', label: 'Luckiest Guy', family: '"Luckiest Guy", display', gfontParam: 'Luckiest+Guy' },
  { id: 'major_mono_display', label: 'Major Mono Display', family: '"Major Mono Display", display', gfontParam: 'Major+Mono+Display' },
  { id: 'mali', label: 'Mali', family: '"Mali", display', gfontParam: 'Mali' },
  { id: 'marck_script', label: 'Marck Script', family: '"Marck Script", display', gfontParam: 'Marck+Script' },
  { id: 'mclaren', label: 'Mclaren', family: '"Mclaren", display', gfontParam: 'Mclaren' },
  { id: 'merienda', label: 'Merienda', family: '"Merienda", display', gfontParam: 'Merienda' },
  { id: 'modak', label: 'Modak', family: '"Modak", display', gfontParam: 'Modak' },
  { id: 'monofett', label: 'Monofett', family: '"Monofett", display', gfontParam: 'Monofett' },
  { id: 'monsieur_la_doulaise', label: 'Monsieur La Doulaise', family: '"Monsieur La Doulaise", display', gfontParam: 'Monsieur+La+Doulaise' },
  { id: 'montserrat_black', label: 'Montserrat Black', family: '"Montserrat Black", display', gfontParam: 'Montserrat+Black:wght@900' },
  { id: 'montserrat_subrayada', label: 'Montserrat Subrayada', family: '"Montserrat Subrayada", display', gfontParam: 'Montserrat+Subrayada' },
  { id: 'mountains_of_christmas', label: 'Mountains of Christmas', family: '"Mountains of Christmas", display', gfontParam: 'Mountains+of+Christmas' },
  { id: 'nabla', label: 'Nabla', family: '"Nabla", display', gfontParam: 'Nabla' },
  { id: 'neuton', label: 'Neuton', family: '"Neuton", display', gfontParam: 'Neuton' },
  { id: 'new_rocker', label: 'New Rocker', family: '"New Rocker", display', gfontParam: 'New+Rocker' },
  { id: 'nixie_one', label: 'Nixie One', family: '"Nixie One", display', gfontParam: 'Nixie+One' },
  { id: 'notable', label: 'Notable', family: '"Notable", display', gfontParam: 'Notable' },
  { id: 'nothing_you_could_do', label: 'Nothing You Could Do', family: '"Nothing You Could Do", display', gfontParam: 'Nothing+You+Could+Do' },
  { id: 'noto_serif_display', label: 'Noto Serif Display', family: '"Noto Serif Display", display', gfontParam: 'Noto+Serif+Display' },
  { id: 'offside', label: 'Offside', family: '"Offside", display', gfontParam: 'Offside' },
  { id: 'oleo_script', label: 'Oleo Script', family: '"Oleo Script", display', gfontParam: 'Oleo+Script' },
  { id: 'oleo_script_swash_caps', label: 'Oleo Script Swash Caps', family: '"Oleo Script Swash Caps", display', gfontParam: 'Oleo+Script+Swash+Caps' },
  { id: 'original_surfer', label: 'Original Surfer', family: '"Original Surfer", display', gfontParam: 'Original+Surfer' },
  { id: 'oswald', label: 'Oswald', family: '"Oswald", display', gfontParam: 'Oswald' },
  { id: 'pathway_gothic_one', label: 'Pathway Gothic One', family: '"Pathway Gothic One", display', gfontParam: 'Pathway+Gothic+One' },
  { id: 'patrick_hand', label: 'Patrick Hand', family: '"Patrick Hand", display', gfontParam: 'Patrick+Hand' },
  { id: 'patua_one', label: 'Patua One', family: '"Patua One", display', gfontParam: 'Patua+One' },
  { id: 'paytone_one', label: 'Paytone One', family: '"Paytone One", display', gfontParam: 'Paytone+One' },
  { id: 'petit_formal_script', label: 'Petit Formal Script', family: '"Petit Formal Script", display', gfontParam: 'Petit+Formal+Script' },
  { id: 'philosopher', label: 'Philosopher', family: '"Philosopher", display', gfontParam: 'Philosopher' },
  { id: 'piedra', label: 'Piedra', family: '"Piedra", display', gfontParam: 'Piedra' },
  { id: 'pirata_one', label: 'Pirata One', family: '"Pirata One", display', gfontParam: 'Pirata+One' },
  { id: 'plaster', label: 'Plaster', family: '"Plaster", display', gfontParam: 'Plaster' },
  { id: 'playball', label: 'Playball', family: '"Playball", display', gfontParam: 'Playball' },
  { id: 'poiret_one', label: 'Poiret One', family: '"Poiret One", display', gfontParam: 'Poiret+One' },
  { id: 'poller_one', label: 'Poller One', family: '"Poller One", display', gfontParam: 'Poller+One' },
  { id: 'prata', label: 'Prata', family: '"Prata", display', gfontParam: 'Prata' },
  { id: 'princess_sofia', label: 'Princess Sofia', family: '"Princess Sofia", display', gfontParam: 'Princess+Sofia' },
  { id: 'prosto_one', label: 'Prosto One', family: '"Prosto One", display', gfontParam: 'Prosto+One' },
  { id: 'quintessential', label: 'Quintessential', family: '"Quintessential", display', gfontParam: 'Quintessential' },
  { id: 'rampart_one', label: 'Rampart One', family: '"Rampart One", display', gfontParam: 'Rampart+One' },
  { id: 'ranchers', label: 'Ranchers', family: '"Ranchers", display', gfontParam: 'Ranchers' },
  { id: 'reggae_one', label: 'Reggae One', family: '"Reggae One", display', gfontParam: 'Reggae+One' },
  { id: 'rhodium_libre', label: 'Rhodium Libre', family: '"Rhodium Libre", display', gfontParam: 'Rhodium+Libre' },
  { id: 'risque', label: 'Risque', family: '"Risque", display', gfontParam: 'Risque' },
  { id: 'roboto_black', label: 'Roboto Black', family: '"Roboto Black", display', gfontParam: 'Roboto+Black:wght@900' },
  { id: 'rock_salt', label: 'Rock Salt', family: '"Rock Salt", display', gfontParam: 'Rock+Salt' },
  { id: 'rowdies', label: 'Rowdies', family: '"Rowdies", display', gfontParam: 'Rowdies' },
  { id: 'rubik_beastly', label: 'Rubik Beastly', family: '"Rubik Beastly", display', gfontParam: 'Rubik+Beastly' },
  { id: 'rubik_bubbles', label: 'Rubik Bubbles', family: '"Rubik Bubbles", display', gfontParam: 'Rubik+Bubbles' },
  { id: 'rubik_burned', label: 'Rubik Burned', family: '"Rubik Burned", display', gfontParam: 'Rubik+Burned' },
  { id: 'rubik_dirt', label: 'Rubik Dirt', family: '"Rubik Dirt", display', gfontParam: 'Rubik+Dirt' },
  { id: 'rubik_distressed', label: 'Rubik Distressed', family: '"Rubik Distressed", display', gfontParam: 'Rubik+Distressed' },
  { id: 'rubik_gemstones', label: 'Rubik Gemstones', family: '"Rubik Gemstones", display', gfontParam: 'Rubik+Gemstones' },
  { id: 'rubik_glitch', label: 'Rubik Glitch', family: '"Rubik Glitch", display', gfontParam: 'Rubik+Glitch' },
  { id: 'rubik_iso', label: 'Rubik Iso', family: '"Rubik Iso", display', gfontParam: 'Rubik+Iso' },
  { id: 'rubik_marker_hatch', label: 'Rubik Marker Hatch', family: '"Rubik Marker Hatch", display', gfontParam: 'Rubik+Marker+Hatch' },
  { id: 'rubik_microbe', label: 'Rubik Microbe', family: '"Rubik Microbe", display', gfontParam: 'Rubik+Microbe' },
  { id: 'rubik_mono_one', label: 'Rubik Mono One', family: '"Rubik Mono One", display', gfontParam: 'Rubik+Mono+One' },
  { id: 'rubik_moonrocks', label: 'Rubik Moonrocks', family: '"Rubik Moonrocks", display', gfontParam: 'Rubik+Moonrocks' },
  { id: 'rubik_pixels', label: 'Rubik Pixels', family: '"Rubik Pixels", display', gfontParam: 'Rubik+Pixels' },
  { id: 'rubik_puddles', label: 'Rubik Puddles', family: '"Rubik Puddles", display', gfontParam: 'Rubik+Puddles' },
  { id: 'rubik_spray_paint', label: 'Rubik Spray Paint', family: '"Rubik Spray Paint", display', gfontParam: 'Rubik+Spray+Paint' },
  { id: 'rubik_storm', label: 'Rubik Storm', family: '"Rubik Storm", display', gfontParam: 'Rubik+Storm' },
  { id: 'rubik_vinyl', label: 'Rubik Vinyl', family: '"Rubik Vinyl", display', gfontParam: 'Rubik+Vinyl' },
  { id: 'rubik_wet_paint', label: 'Rubik Wet Paint', family: '"Rubik Wet Paint", display', gfontParam: 'Rubik+Wet+Paint' },
  { id: 'sail', label: 'Sail', family: '"Sail", display', gfontParam: 'Sail' },
  { id: 'sansita', label: 'Sansita', family: '"Sansita", display', gfontParam: 'Sansita' },
  { id: 'sansita_swashed', label: 'Sansita Swashed', family: '"Sansita Swashed", display', gfontParam: 'Sansita+Swashed' },
  { id: 'satisfy', label: 'Satisfy', family: '"Satisfy", display', gfontParam: 'Satisfy' },
  { id: 'sedgwick_ave_display', label: 'Sedgwick Ave Display', family: '"Sedgwick Ave Display", display', gfontParam: 'Sedgwick+Ave+Display' },
  { id: 'shadows_into_light', label: 'Shadows Into Light', family: '"Shadows Into Light", display', gfontParam: 'Shadows+Into+Light' },
  { id: 'shojumaru', label: 'Shojumaru', family: '"Shojumaru", display', gfontParam: 'Shojumaru' },
  { id: 'shrikhand', label: 'Shrikhand', family: '"Shrikhand", display', gfontParam: 'Shrikhand' },
  { id: 'sigmar', label: 'Sigmar', family: '"Sigmar", display', gfontParam: 'Sigmar' },
  { id: 'sigmar_one', label: 'Sigmar One', family: '"Sigmar One", display', gfontParam: 'Sigmar+One' },
  { id: 'silkscreen', label: 'Silkscreen', family: '"Silkscreen", display', gfontParam: 'Silkscreen' },
  { id: 'six_caps', label: 'Six Caps', family: '"Six Caps", display', gfontParam: 'Six+Caps' },
  { id: 'skranji', label: 'Skranji', family: '"Skranji", display', gfontParam: 'Skranji' },
  { id: 'slabo_27px', label: 'Slabo 27px', family: '"Slabo 27px", display', gfontParam: 'Slabo+27px' },
  { id: 'smokum', label: 'Smokum', family: '"Smokum", display', gfontParam: 'Smokum' },
  { id: 'snowburst_one', label: 'Snowburst One', family: '"Snowburst One", display', gfontParam: 'Snowburst+One' },
  { id: 'sofadi_one', label: 'Sofadi One', family: '"Sofadi One", display', gfontParam: 'Sofadi+One' },
  { id: 'sonsie_one', label: 'Sonsie One', family: '"Sonsie One", display', gfontParam: 'Sonsie+One' },
  { id: 'spicy_rice', label: 'Spicy Rice', family: '"Spicy Rice", display', gfontParam: 'Spicy+Rice' },
  { id: 'squada_one', label: 'Squada One', family: '"Squada One", display', gfontParam: 'Squada+One' },
  { id: 'stalemate', label: 'Stalemate', family: '"Stalemate", display', gfontParam: 'Stalemate' },
  { id: 'stalinist_one', label: 'Stalinist One', family: '"Stalinist One", display', gfontParam: 'Stalinist+One' },
  { id: 'stardos_stencil', label: 'Stardos Stencil', family: '"Stardos Stencil", display', gfontParam: 'Stardos+Stencil' },
  { id: 'stick', label: 'Stick', family: '"Stick", display', gfontParam: 'Stick' },
  { id: 'stint_ultra_condensed', label: 'Stint Ultra Condensed', family: '"Stint Ultra Condensed", display', gfontParam: 'Stint+Ultra+Condensed' },
  { id: 'stint_ultra_expanded', label: 'Stint Ultra Expanded', family: '"Stint Ultra Expanded", display', gfontParam: 'Stint+Ultra+Expanded' },
  { id: 'story_script', label: 'Story Script', family: '"Story Script", display', gfontParam: 'Story+Script' },
  { id: 'suez_one', label: 'Suez One', family: '"Suez One", display', gfontParam: 'Suez+One' },
  { id: 'syncopate', label: 'Syncopate', family: '"Syncopate", display', gfontParam: 'Syncopate' },
  { id: 'tangerine', label: 'Tangerine', family: '"Tangerine", display', gfontParam: 'Tangerine' },
  { id: 'tilt_neon', label: 'Tilt Neon', family: '"Tilt Neon", display', gfontParam: 'Tilt+Neon' },
  { id: 'tilt_prism', label: 'Tilt Prism', family: '"Tilt Prism", display', gfontParam: 'Tilt+Prism' },
  { id: 'tilt_warp', label: 'Tilt Warp', family: '"Tilt Warp", display', gfontParam: 'Tilt+Warp' },
  { id: 'titan_one', label: 'Titan One', family: '"Titan One", display', gfontParam: 'Titan+One' },
  { id: 'tourney', label: 'Tourney', family: '"Tourney", display', gfontParam: 'Tourney' },
  { id: 'trade_winds', label: 'Trade Winds', family: '"Trade Winds", display', gfontParam: 'Trade+Winds' },
  { id: 'train_one', label: 'Train One', family: '"Train One", display', gfontParam: 'Train+One' },
  { id: 'ultra', label: 'Ultra', family: '"Ultra", display', gfontParam: 'Ultra' },
  { id: 'underdog', label: 'Underdog', family: '"Underdog", display', gfontParam: 'Underdog' },
  { id: 'unica_one', label: 'Unica One', family: '"Unica One", display', gfontParam: 'Unica+One' },
  { id: 'unifrakturmaguntia', label: 'Unifrakturmaguntia', family: '"Unifrakturmaguntia", display', gfontParam: 'Unifrakturmaguntia' },
  { id: 'unkempt', label: 'Unkempt', family: '"Unkempt", display', gfontParam: 'Unkempt' },
  { id: 'vampiro_one', label: 'Vampiro One', family: '"Vampiro One", display', gfontParam: 'Vampiro+One' },
  { id: 'vast_shadow', label: 'Vast Shadow', family: '"Vast Shadow", display', gfontParam: 'Vast+Shadow' },
  { id: 'vt323', label: 'VT323', family: '"VT323", display', gfontParam: 'VT323' },
  { id: 'wallpoet', label: 'Wallpoet', family: '"Wallpoet", display', gfontParam: 'Wallpoet' },
  { id: 'warnes', label: 'Warnes', family: '"Warnes", display', gfontParam: 'Warnes' },
  { id: 'wendy_one', label: 'Wendy One', family: '"Wendy One", display', gfontParam: 'Wendy+One' },
  { id: 'yellowtail', label: 'Yellowtail', family: '"Yellowtail", display', gfontParam: 'Yellowtail' },
  { id: 'yeseva_one', label: 'Yeseva One', family: '"Yeseva One", display', gfontParam: 'Yeseva+One' },
  { id: 'zen_dots', label: 'Zen Dots', family: '"Zen Dots", display', gfontParam: 'Zen+Dots' },
  { id: 'zen_tokyo_zoo', label: 'Zen Tokyo Zoo', family: '"Zen Tokyo Zoo", display', gfontParam: 'Zen+Tokyo+Zoo' },
];

/** Inject a Google Fonts <link> for the given family param, only once per param. */
export function ensureGoogleFontLoaded(gfontParam: string) {
  if (!gfontParam) return;
  if (typeof document === 'undefined') return;
  const id = `gfont-${gfontParam.replace(/[^a-zA-Z0-9]/g, '-')}`;
  if (document.getElementById(id)) return;
  const link = document.createElement('link');
  link.id = id;
  link.rel = 'stylesheet';
  link.href = `https://fonts.googleapis.com/css2?family=${gfontParam}&display=swap`;
  document.head.appendChild(link);
}

export function getSplashFontById(id: string | undefined | null): SplashFont {
  if (!id) return SPLASH_FONTS[0];
  return SPLASH_FONTS.find(f => f.id === id) || SPLASH_FONTS[0];
}
